import { test, expect, _electron as electron } from '@playwright/test'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import electronExecutable from 'electron'
import { createCanvas } from '@napi-rs/canvas'

const texBin = process.env.REFORA_TEX_BIN || '/Library/TeX/texbin'

test('LaTeX source, workspace image, AI refresh and PDF preview', async () => {
  test.skip(!fs.existsSync(path.join(texBin, 'latexmk')), 'Set REFORA_TEX_BIN to a TeX installation containing latexmk')
  test.setTimeout(180_000)
  const folder = fs.mkdtempSync(path.join(os.tmpdir(), 'refora-latex-e2e-'))
  const userData = path.join(folder, 'user')
  const library = path.join(folder, 'library')
  fs.mkdirSync(userData)
  fs.mkdirSync(library)
  fs.writeFileSync(path.join(userData, 'refora-prefs.json'), JSON.stringify({ libraryFolderPath: library }))
  const env = { ...process.env, REFORA_E2E_USER_DATA_DIR: userData, REFORA_TEX_BIN: texBin } as Record<string, string>
  delete env.ELECTRON_RUN_AS_NODE
  const application = await electron.launch({ executablePath: String(electronExecutable), args: [path.resolve('tests/e2e/electron-main.mjs')], env })
  try {
    const page = await application.firstWindow()
    const workspace = await page.evaluate(() => window.api.workspaces.create('LaTeX E2E'))
    await page.evaluate(() => window.api.workspaces.create('Other workspace'))
    const imagePath = path.join(folder, 'figure.png')
    const fixtureCanvas = createCanvas(60, 30)
    const context = fixtureCanvas.getContext('2d')
    context.fillStyle = '#ef765f'
    context.fillRect(0, 0, 60, 30)
    fs.writeFileSync(imagePath, fixtureCanvas.toBuffer('image/png'))
    await page.evaluate(() => {
      const input = document.createElement('input')
      input.type = 'file'
      input.id = 'latex-file-fixture'
      document.body.append(input)
    })
    const cdp = await page.context().newCDPSession(page)
    const { root } = await cdp.send('DOM.getDocument')
    const { nodeId } = await cdp.send('DOM.querySelector', { nodeId: root.nodeId, selector: '#latex-file-fixture' })
    await cdp.send('DOM.setFileInputFiles', { nodeId, files: [imagePath] })
    await page.evaluate(async (id) => {
      const input = document.querySelector<HTMLInputElement>('#latex-file-fixture')!
      const assetPath = await window.api.getPathForFile(input.files![0])
      const result = await window.api.workspaceAssets.addFiles(id, [assetPath])
      if (result.errors.length) throw new Error(result.errors[0].message)
      input.remove()
    }, workspace.id)
    await page.evaluate(id => window.api.workspaceNotes.create(id, 'Companion Markdown', '# Companion note', 'markdown', { x: 20, y: 20 }), workspace.id)
    await page.reload()
    await page.getByRole('button', { name: 'Other workspace', exact: true }).click()
    await page.getByRole('button', { name: 'LaTeX E2E', exact: true }).click()
    await page.getByRole('button', { name: 'Companion Markdown', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Companion Markdown', exact: true })).toBeVisible()
    await page.getByRole('tab', { name: 'LaTeX E2E', exact: true }).click()
    await page.getByRole('button', { name: 'Add LaTeX document', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'LaTeX', exact: true })).toHaveCount(0)
    await expect(page.getByRole('tab', { name: 'LaTeX E2E', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(page.getByRole('tab', { name: 'Companion Markdown', exact: true })).toBeVisible()
    await expect(page.locator('.board-surface')).toBeVisible()
    await page.getByLabel('Project title', { exact: true }).fill('Test paper')
    await page.getByRole('dialog', { name: 'Add LaTeX document', exact: true }).getByRole('button', { name: 'New project', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Add LaTeX document', exact: true })).toHaveCount(0)
    await expect(page.getByRole('tab', { name: 'LaTeX E2E', exact: true })).toHaveAttribute('aria-selected', 'true')
    const latexCard = page.locator('[data-card-kind="latex"]').filter({ hasText: 'Test paper' })
    await expect(latexCard).toBeVisible()
    const actions = page.getByTestId('workspace-floating-actions')
    await expect(actions.getByRole('separator')).toHaveCount(1)
    expect(await actions.getByRole('separator').evaluate(element => Array.from(element.parentElement!.children).filter(child => child.tagName === 'BUTTON').filter(child => Boolean(child.compareDocumentPosition(element) & Node.DOCUMENT_POSITION_FOLLOWING)).length)).toBe(4)
    const initialCard = await page.evaluate(async id => (await window.api.workspaceItems.list(id)).find(item => item.kind === 'latex'), workspace.id)
    expect(initialCard).toMatchObject({ width: 300, height: 112 })
    await expect(latexCard.getByText('main.tex', { exact: true })).toBeInViewport({ ratio: 1 })
    await page.screenshot({ path: path.join(folder, 'latex-workspace-card.png'), fullPage: true })
    await latexCard.getByRole('button', { name: 'Test paper', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Test paper', exact: true })).toBeInViewport()
    await expect(page.getByRole('button', { name: 'Current file: main.tex', exact: true })).toBeVisible()
    await expect(page.getByRole('tab', { name: 'main.tex', exact: true })).toHaveCount(0)
    await expect(page.locator('.latex-editor-region')).not.toContainText('main.tex')
    const activeView = page.locator('.latex-workspace:visible')
    await expect(activeView.locator('.latex-document-toolbar')).toHaveCount(0)
    await expect(activeView.locator('.latex-topbar').getByRole('button', { name: 'Current file: main.tex', exact: true })).toBeVisible()
    await expect(activeView.locator('.latex-topbar').getByRole('button', { name: 'Compile ⌘↵', exact: true })).toBeVisible()
    const editor = activeView.getByLabel('LaTeX source', { exact: true })
    await editor.fill('\\documentclass{article}\n\\usepackage{graphicx}\n\\begin{document}\nLocal source.\n\\end{document}\n')
    await expect.poll(() => page.locator('.latex-topbar').evaluate((element) => element.getBoundingClientRect().height)).toBeLessThanOrEqual(50)
    const navigation = activeView.getByRole('button', { name: 'Document navigation', exact: true })
    const find = activeView.locator('.latex-topbar').getByRole('textbox', { name: 'Find', exact: true })
    await expect(navigation).toBeInViewport({ ratio: 1 })
    await expect(find).toBeInViewport({ ratio: 1 })
    await navigation.click()
    await expect(navigation).toHaveAttribute('aria-pressed', 'true')
    await activeView.getByRole('tab', { name: 'Project files', exact: true }).press('Escape')
    await expect(navigation).toHaveAttribute('aria-pressed', 'false')
    await expect(navigation).toBeFocused()
    await find.click()
    const search = activeView.getByRole('textbox', { name: 'Find', exact: true })
    await search.fill('Local')
    expect(await search.evaluate(element => { const style = getComputedStyle(element); return element.clientWidth - parseFloat(style.paddingLeft) - parseFloat(style.paddingRight) })).toBeGreaterThanOrEqual(60)
    await search.press('Enter')
    await expect(search).toBeFocused()
    await search.press('Escape')
    await expect(find).toBeVisible()
    await expect(find).toHaveValue('')
    await expect(editor).toBeFocused()
    await page.getByRole('button', { name: 'Current file: main.tex', exact: true }).click()
    await page.getByRole('tab', { name: 'Workspace figures', exact: true }).click()
    await page.getByRole('button', { name: 'figure.png', exact: true }).click()
    await expect(editor).toHaveValue(/includegraphics/)
    await page.getByRole('button', { name: 'Compile ⌘↵', exact: true }).click()
    await expect(page.locator('.latex-pdf canvas')).toBeVisible({ timeout: 140_000 })
    await expect(page.locator('.latex-pdf-toolbar')).toContainText('1 / 1')
    await expect.poll(() => page.locator('.latex-pdf-scroll').evaluate((element) => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
    await expect(page.locator('.latex-pdf canvas')).toBeInViewport()
    await expect.poll(() => page.locator('.latex-pdf canvas').evaluate((element) => {
      const canvas = element as HTMLCanvasElement
      const pixels = canvas.getContext('2d')!.getImageData(0, 0, canvas.width, canvas.height).data
      let figurePixels = 0
      for (let index = 0; index < pixels.length; index += 4) {
        if (Math.abs(pixels[index] - 239) < 5 && Math.abs(pixels[index + 1] - 118) < 5 && Math.abs(pixels[index + 2] - 95) < 5) figurePixels++
      }
      return figurePixels
    })).toBeGreaterThan(100)
    const active = await page.evaluate(id => window.api.latex.execute(id, { action: 'active' }), workspace.id)
    expect(active.file?.content).toContain('includegraphics')
    await page.evaluate(async ({ id, current }) => {
      await window.api.latex.execute(id, { action: 'write', projectId: current.project!.id, path: current.file!.path, content: current.file!.content.replace('Local source.', 'AI-edited source.'), expectedHash: current.file!.hash })
    }, { id: workspace.id, current: active })
    await page.getByRole('button', { name: 'Source', exact: true }).click()
    await expect(editor).toHaveValue(/AI-edited source/)
    await expect(editor).toBeInViewport()
    await page.getByRole('button', { name: 'Compile ⌘↵', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Compile ⌘↵', exact: true })).toBeEnabled({ timeout: 140_000 })
    await expect(page.locator('.latex-preview-notice')).toHaveCount(0)
    await expect(page.locator('.latex-pdf')).not.toContainText('Error')
    await page.screenshot({ path: path.join(folder, 'latex.png'), fullPage: true })
    await page.getByRole('button', { name: 'Enter fullscreen', exact: true }).click()
    await page.getByRole('button', { name: 'Source and PDF', exact: true }).click()
    await expect(editor).toBeInViewport()
    await expect(page.locator('.latex-pdf canvas')).toBeInViewport()
    await page.screenshot({ path: path.join(folder, 'latex-wide.png'), fullPage: true })
    await page.getByRole('button', { name: 'Exit fullscreen', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Close Test paper', exact: true })).toBeInViewport({ ratio: 1 })
    await page.getByRole('button', { name: 'Enter fullscreen', exact: true }).click()
    await page.getByRole('button', { name: 'Project actions', exact: true }).click()
    await page.getByRole('button', { name: 'New project', exact: true }).click()
    await page.getByLabel('Project title', { exact: true }).fill('Second paper')
    await page.getByRole('dialog', { name: 'New project', exact: true }).getByRole('button', { name: 'New project', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Second paper', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(page.getByRole('tab', { name: 'Test paper', exact: true })).toBeVisible()
    await editor.fill('\\documentclass{article}\n\\begin{document}\nSecond project source.\n\\end{document}\n')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect.poll(async () => (await page.evaluate(id => window.api.latex.execute(id, { action: 'active' }), workspace.id)).file?.content).toContain('Second project source.')
    await page.getByRole('tab', { name: 'Test paper', exact: true }).click()
    await expect(editor).toHaveValue(/AI-edited source/)
    await expect(activeView.locator('.latex-pdf canvas')).toBeVisible()
    await expect.poll(async () => (await page.evaluate(id => window.api.latex.execute(id, { action: 'active' }), workspace.id)).project?.id).toBe(active.project!.id)
    await page.getByRole('button', { name: 'Close Second paper', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Second paper', exact: true })).toHaveCount(0)
    await expect.poll(async () => (await page.evaluate(id => window.api.latex.execute(id, { action: 'active' }), workspace.id)).project?.id).toBe(active.project!.id)
    await page.getByRole('button', { name: 'Project actions', exact: true }).click()
    await page.getByRole('button', { name: 'Open project', exact: true }).click()
    await page.getByRole('dialog', { name: 'Your projects', exact: true }).getByRole('button', { name: /^Second paper/ }).click()
    await expect(editor).toHaveValue(/Second project source/)
    await expect(page.getByRole('tab', { name: 'Second paper', exact: true })).toHaveAttribute('aria-selected', 'true')
    await page.screenshot({ path: path.join(folder, 'latex-project-tabs.png'), fullPage: true })
    await page.getByRole('button', { name: 'Close Second paper', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Test paper', exact: true })).toHaveAttribute('aria-selected', 'true')
    await page.getByRole('tab', { name: 'LaTeX E2E', exact: true }).click()
    await expect(latexCard).toBeVisible()
    await expect.poll(async () => (await page.evaluate(id => window.api.latex.execute(id, { action: 'active' }), workspace.id)).active).toBeNull()
    await page.getByRole('tab', { name: 'Companion Markdown', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Test paper', exact: true })).toBeVisible()
    await page.getByRole('tab', { name: 'Test paper', exact: true }).click()
    await expect(editor).toHaveValue(/AI-edited source/)
    await page.getByRole('tab', { name: 'Other workspace', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Test paper', exact: true })).toBeVisible()
    await expect.poll(async () => (await page.evaluate(id => window.api.latex.execute(id, { action: 'active' }), workspace.id)).active).toBeNull()
    await page.getByRole('tab', { name: 'Test paper', exact: true }).click()
    await expect(editor).toHaveValue(/AI-edited source/)
    await expect(activeView.locator('.latex-preview-region canvas').first()).toBeVisible()
    await expect.poll(async () => (await page.evaluate(id => window.api.latex.execute(id, { action: 'active' }), workspace.id)).project?.id).toBe(active.project!.id)
    await page.getByRole('button', { name: 'Close Other workspace', exact: true }).click()
    await page.getByRole('tab', { name: 'LaTeX E2E', exact: true }).click()
    await page.getByRole('button', { name: 'Close LaTeX E2E', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Test paper', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(editor).toHaveValue(/AI-edited source/)
    await page.getByRole('tab', { name: 'LaTeX E2E', exact: true }).click()
    const savedCard = await page.evaluate(async ({ id, projectId }) => (await window.api.workspaceItems.list(id)).find(item => item.latexId === projectId)!, { id: workspace.id, projectId: active.project!.id })
    await page.evaluate(async id => { await window.api.workspaceItems.move(id, 80, 280, 8); await window.api.workspaceItems.resize(id, 340, 210) }, savedCard.id)
    await page.reload()
    await page.getByRole('button', { name: 'LaTeX E2E', exact: true }).click()
    const restoredCard = await page.evaluate(async ({ id, cardId }) => (await window.api.workspaceItems.list(id)).find(item => item.id === cardId)!, { id: workspace.id, cardId: savedCard.id })
    expect(restoredCard).toMatchObject({ x: 80, y: 280, width: 340, height: 210, latexId: active.project!.id })
    await latexCard.getByRole('button', { name: 'Remove card (keep source files)', exact: true }).click()
    await expect(latexCard).toHaveCount(0)
    const retained = await page.evaluate(({ id, projectId }) => window.api.latex.execute(id, { action: 'read', projectId, path: 'main.tex' }), { id: workspace.id, projectId: active.project!.id })
    expect(retained.file?.content).toContain('AI-edited source')
    await page.reload()
    await page.getByRole('button', { name: 'LaTeX E2E', exact: true }).click()
    await expect(latexCard).toHaveCount(0)
    await page.getByRole('button', { name: 'Add LaTeX document', exact: true }).click()
    await page.getByRole('dialog', { name: 'Add LaTeX document', exact: true }).getByRole('button', { name: 'Add card', exact: true }).click()
    await expect(latexCard).toBeVisible()
    await latexCard.getByRole('button', { name: 'Test paper', exact: true }).click()
    await expect(editor).toHaveValue(/AI-edited source/)
  } finally {
    await application.close()
  }
})
