export const IpcChannel = {
  Bootstrap: 'app:bootstrap',

  DocumentsList: 'documents:list',
  DocumentsCount: 'documents:count',
  DocumentsSearch: 'documents:search',
  DocumentsGet: 'documents:get',
  DocumentsUpdate: 'documents:update',
  DocumentsSetStarred: 'documents:setStarred',
  DocumentsDelete: 'documents:delete',
  DocumentsBulkDelete: 'documents:bulkDelete',
  DocumentsBulkCategorize: 'documents:bulkCategorize',
  DocumentsBulkRefreshMetadata: 'documents:bulkRefreshMetadata',
  DocumentsOpenPdf: 'documents:openPdf',
  DocumentsReadPdf: 'documents:readPdf',
  DocumentsPdfAnnotationsGet: 'documents:pdfAnnotations:get',
  DocumentsPdfAnnotationsSet: 'documents:pdfAnnotations:set',
  DocumentsOpenInFinder: 'documents:openInFinder',
  DocumentsRefreshMetadata: 'documents:refreshMetadata',
  DocumentsRelocateFile: 'documents:relocateFile',
  DocumentsRestoreFile: 'documents:restoreFile',

  GlobalSearch: 'search:global',

  ImportAddFiles: 'import:addFiles',
  ImportAddFolder: 'import:addFolder',
  ImportFromJson: 'import:fromJson',
  ImportFromZotero: 'import:fromZotero',
  ImportFromMendeley: 'import:fromMendeley',
  ImportFromIdentifier: 'import:fromIdentifier',

  CategoriesList: 'categories:list',
  CategoriesCreate: 'categories:create',
  CategoriesRename: 'categories:rename',
  CategoriesDelete: 'categories:delete',
  CategoriesAssign: 'categories:assign',
  CategoriesUnassign: 'categories:unassign',

  WatchList: 'watch:list',
  WatchAdd: 'watch:add',
  WatchRemove: 'watch:remove',
  WatchToggle: 'watch:toggle',

  DialogOpenDirectory: 'dialog:openDirectory',

  LibrarySwitch: 'library:switch',

  SettingsGet: 'settings:get',
  SettingsSet: 'settings:set',

  WebSearchConfigGet: 'webSearch:config:get',
  WebSearchConfigUpdate: 'webSearch:config:update',
  WebSearchTest: 'webSearch:test',

  MineruStatus: 'mineru:status',
  MineruChooseInstallRoot: 'mineru:chooseInstallRoot',
  MineruInstall: 'mineru:install',
  MineruCancelInstall: 'mineru:cancelInstall',
  MineruUninstall: 'mineru:uninstall',

  OcrGetState: 'ocr:getState',
  OcrStart: 'ocr:start',
  OcrCancel: 'ocr:cancel',
  OcrReadMarkdown: 'ocr:readMarkdown',

  ExportToJson: 'export:toJson',
  ExportToBibtex: 'export:toBibtex',
  ExportBibtexString: 'export:bibtexString',

  ClipboardWriteText: 'clipboard:writeText',
  ClipboardCopyMarkdown: 'clipboard:copyMarkdown',
  ClipboardCopyWorkspaceAsset: 'clipboard:copyWorkspaceAsset',

  WorkspacesList: 'workspaces:list',
  WorkspacesCreate: 'workspaces:create',
  WorkspacesRename: 'workspaces:rename',
  WorkspacesDelete: 'workspaces:delete',
  WorkspacesOpenSandbox: 'workspaces:openSandbox',

  WorkspaceItemsList: 'workspaceItems:list',
  WorkspaceItemsAdd: 'workspaceItems:add',
  WorkspaceItemsRemove: 'workspaceItems:remove',
  WorkspaceItemsReorder: 'workspaceItems:reorder',
  WorkspaceItemsResize: 'workspaceItems:resize',
  WorkspaceItemsMove: 'workspaceItems:move',

  WorkspaceAssetsList: 'workspaceAssets:list',
  WorkspaceAssetsAddFiles: 'workspaceAssets:addFiles',
  WorkspaceAssetsTextPreview: 'workspaceAssets:textPreview',
  WorkspaceAssetsOpen: 'workspaceAssets:open',
  WorkspaceAssetsReveal: 'workspaceAssets:reveal',
  WorkspaceAssetsDelete: 'workspaceAssets:delete',

  WorkspaceFilesAdd: 'workspaceFiles:add',

  WorkspaceCanvasGet: 'workspaceCanvas:get',
  WorkspaceCanvasUpdate: 'workspaceCanvas:update',

  WorkspaceConnectionsList: 'workspaceConnections:list',
  WorkspaceConnectionsCreate: 'workspaceConnections:create',
  WorkspaceConnectionsDelete: 'workspaceConnections:delete',

  WorkspaceNotesList: 'workspaceNotes:list',
  WorkspaceNotesCreate: 'workspaceNotes:create',
  WorkspaceNotesUpdate: 'workspaceNotes:update',
  WorkspaceNotesDelete: 'workspaceNotes:delete',

  AiProvidersList: 'ai:providers:list',
  AiProvidersCreate: 'ai:providers:create',
  AiProvidersUpdate: 'ai:providers:update',
  AiProvidersDelete: 'ai:providers:delete',
  AiProvidersTest: 'ai:providers:test',
  AiProvidersListModels: 'ai:providers:listModels',

  AiDocTextGet: 'ai:docText:get',
  AiSummarize: 'ai:summarize',
  AiSummaryGet: 'ai:summary:get',

  AiChatSend: 'ai:chat:send',
  AiChatHistory: 'ai:chat:history',
  AiChatThreads: 'ai:chat:threads',
  AiUsageStats: 'ai:usage:stats',
  AiChatTraces: 'ai:chat:traces',
  AiChatRun: 'ai:chat:run',
  AiChatCancel: 'ai:chat:cancel',
  AiChatResume: 'ai:chat:resume',
  AiChatPendingInterrupt: 'ai:chat:pendingInterrupt',
  AiChatDeleteThread: 'ai:chat:deleteThread',
  AiChatRenameThread: 'ai:chat:renameThread',
  AiWorkspaceMemoriesList: 'ai:workspaceMemories:list',
  AiWorkspaceMemoryUpdate: 'ai:workspaceMemories:update',
  AiWorkspaceMemoryDelete: 'ai:workspaceMemories:delete',

  AiReportsList: 'ai:reports:list',
  AiReportsDelete: 'ai:reports:delete',
  AiReportsUpdate: 'ai:reports:update',

  EventDocumentUpdated: 'document:updated',
  EventWindowFocusChanged: 'window:focus-changed',
  EventImportProgress: 'import:progress',
  EventImportToast: 'import:toast',
  EventMenuExportBibtex: 'menu:export-bibtex',
  EventMenuImportZotero: 'menu:import-zotero',
  EventMenuImportMendeley: 'menu:import-mendeley',
  EventMenuImportIdentifier: 'menu:import-identifier',
  EventLibraryScanning: 'library:scanning',
  EventLibrarySwitched: 'library:switched',
  EventAiSummaryUpdated: 'ai:summary:updated',
  EventAiSummaryError: 'ai:summary:error',
  EventAiChatToken: 'ai:chat:token',
  EventAiChatReasoning: 'ai:chat:reasoning',
  EventAiChatDone: 'ai:chat:done',
  EventAiChatError: 'ai:chat:error',
  EventAiChatTrace: 'ai:chat:trace',
  EventAiChatInterrupted: 'ai:chat:interrupted',
  EventAiChatRunStatus: 'ai:chat:runStatus',
  EventAiChatTitleUpdated: 'ai:chat:titleUpdated',
  EventAiReportCreated: 'ai:report:created',
  EventWorkspaceItemsChanged: 'workspace:items:changed',
  EventMineruInstallProgress: 'mineru:installProgress',
  EventOcrProgress: 'ocr:progress',
  EventOcrCompleted: 'ocr:completed',
  EventOcrError: 'ocr:error'
} as const
