export const IpcChannel = {
  Bootstrap: 'app:bootstrap',
  RendererFlushComplete: 'app:renderer-flush-complete',

  DocumentsList: 'documents:list',
  DocumentsCount: 'documents:count',
  DocumentsSearch: 'documents:search',
  DocumentsGet: 'documents:get',
  DocumentsUpdate: 'documents:update',
  DocumentsSetStarred: 'documents:setStarred',
  DocumentsDelete: 'documents:delete',
  DocumentsBulkDelete: 'documents:bulkDelete',
  DocumentsBulkCategorize: 'documents:bulkCategorize',
  DocumentsBulkRefreshMetadata: 'documents:bulkRefreshMetadata',
  DocumentsOpenPdf: 'documents:openPdf',
  DocumentsReadPdfRange: 'documents:readPdfRange',
  DocumentsPdfAnnotationsGet: 'documents:pdfAnnotations:get',
  DocumentsPdfAnnotationsSet: 'documents:pdfAnnotations:set',
  DocumentsOpenInFinder: 'documents:openInFinder',
  DocumentsRefreshMetadata: 'documents:refreshMetadata',
  DocumentsRelocateFile: 'documents:relocateFile',
  DocumentsRestoreFile: 'documents:restoreFile',

  GlobalSearch: 'search:global',

  ImportAddFiles: 'import:addFiles',
  ImportAddFolder: 'import:addFolder',
  ImportFromJson: 'import:fromJson',
  ImportFromZotero: 'import:fromZotero',
  ImportFromMendeley: 'import:fromMendeley',
  ImportFromIdentifier: 'import:fromIdentifier',

  CategoriesList: 'categories:list',
  CategoriesCreate: 'categories:create',
  CategoriesRename: 'categories:rename',
  CategoriesDelete: 'categories:delete',
  CategoriesAssign: 'categories:assign',
  CategoriesUnassign: 'categories:unassign',

  WatchList: 'watch:list',
  WatchAdd: 'watch:add',
  WatchRemove: 'watch:remove',
  WatchToggle: 'watch:toggle',

  DialogOpenDirectory: 'dialog:openDirectory',
  FileAuthorizeDropped: 'file:authorizeDropped',

  LibrarySwitch: 'library:switch',

  SettingsGet: 'settings:get',
  SettingsSet: 'settings:set',
  AppearanceSetThemeSource: 'appearance:setThemeSource',

  SyncStatus: 'sync:status',
  SyncSignIn: 'sync:signIn',
  SyncSignUp: 'sync:signUp',
  SyncResendConfirmation: 'sync:resendConfirmation',
  SyncSignOut: 'sync:signOut',
  SyncSetEnabled: 'sync:setEnabled',

  WebSearchConfigGet: 'webSearch:config:get',
  WebSearchConfigUpdate: 'webSearch:config:update',
  WebSearchTest: 'webSearch:test',

  MineruStatus: 'mineru:status',
  MineruChooseInstallRoot: 'mineru:chooseInstallRoot',
  MineruInstall: 'mineru:install',
  MineruCancelInstall: 'mineru:cancelInstall',
  MineruUninstall: 'mineru:uninstall',

  OcrGetState: 'ocr:getState',
  OcrStart: 'ocr:start',
  OcrCancel: 'ocr:cancel',
  OcrReadMarkdown: 'ocr:readMarkdown',

  ExportToJson: 'export:toJson',
  ExportToBibtex: 'export:toBibtex',
  ExportBibtexString: 'export:bibtexString',

  ClipboardWriteText: 'clipboard:writeText',
  ClipboardCopyMarkdown: 'clipboard:copyMarkdown',
  ClipboardCopyWorkspaceAsset: 'clipboard:copyWorkspaceAsset',

  WorkspacesList: 'workspaces:list',
  WorkspacesCreate: 'workspaces:create',
  WorkspacesRename: 'workspaces:rename',
  WorkspacesDelete: 'workspaces:delete',
  WorkspacesOpenSandbox: 'workspaces:openSandbox',

  WorkspaceItemsList: 'workspaceItems:list',
  WorkspaceItemsAdd: 'workspaceItems:add',
  WorkspaceItemsRemove: 'workspaceItems:remove',
  WorkspaceItemsReorder: 'workspaceItems:reorder',
  WorkspaceItemsResize: 'workspaceItems:resize',
  WorkspaceItemsMove: 'workspaceItems:move',

  WorkspaceAssetsList: 'workspaceAssets:list',
  WorkspaceAssetsAddFiles: 'workspaceAssets:addFiles',
  WorkspaceAssetsTextPreview: 'workspaceAssets:textPreview',
  WorkspaceAssetsOpen: 'workspaceAssets:open',
  WorkspaceAssetsReveal: 'workspaceAssets:reveal',
  WorkspaceAssetsDelete: 'workspaceAssets:delete',

  WorkspaceFilesAdd: 'workspaceFiles:add',

  WorkspaceCanvasGet: 'workspaceCanvas:get',
  WorkspaceCanvasUpdate: 'workspaceCanvas:update',

  WorkspaceConnectionsList: 'workspaceConnections:list',
  WorkspaceConnectionsCreate: 'workspaceConnections:create',
  WorkspaceConnectionsDelete: 'workspaceConnections:delete',

  WorkspaceNotesList: 'workspaceNotes:list',
  WorkspaceNotesCreate: 'workspaceNotes:create',
  WorkspaceNotesUpdate: 'workspaceNotes:update',
  WorkspaceNotesDelete: 'workspaceNotes:delete',

  AiProvidersList: 'ai:providers:list',
  AiProvidersCreate: 'ai:providers:create',
  AiProvidersUpdate: 'ai:providers:update',
  AiProvidersDelete: 'ai:providers:delete',
  AiProvidersTest: 'ai:providers:test',
  AiProvidersListModels: 'ai:providers:listModels',

  AgentProfilesList: 'ai:agentProfiles:list',
  AgentProfilesCreate: 'ai:agentProfiles:create',
  AgentProfilesUpdate: 'ai:agentProfiles:update',
  AgentProfilesDelete: 'ai:agentProfiles:delete',
  AgentProfilesTest: 'ai:agentProfiles:test',
  AgentProfilesListModels: 'ai:agentProfiles:listModels',
  AgentProfilesScanRuntimes: 'ai:agentProfiles:scanRuntimes',

  AiDocTextGet: 'ai:docText:get',
  AiSummarize: 'ai:summarize',
  AiSummaryGet: 'ai:summary:get',

  AiChatSend: 'ai:chat:send',
  AiChatHistory: 'ai:chat:history',
  AiChatThreads: 'ai:chat:threads',
  AiUsageStats: 'ai:usage:stats',
  AiChatTraces: 'ai:chat:traces',
  AiChatRun: 'ai:chat:run',
  AiChatCancel: 'ai:chat:cancel',
  AiChatResume: 'ai:chat:resume',
  AiChatPendingInterrupt: 'ai:chat:pendingInterrupt',
  AiChatDeleteThread: 'ai:chat:deleteThread',
  AiChatRenameThread: 'ai:chat:renameThread',
  AiWorkspaceMemoriesList: 'ai:workspaceMemories:list',
  AiWorkspaceMemoryUpdate: 'ai:workspaceMemories:update',
  AiWorkspaceMemoryDelete: 'ai:workspaceMemories:delete',

  AiReportsList: 'ai:reports:list',
  AiReportsDelete: 'ai:reports:delete',
  AiReportsUpdate: 'ai:reports:update',

  EventDocumentUpdated: 'document:updated',
  EventRendererFlushRequested: 'app:renderer-flush-requested',
  EventWindowFocusChanged: 'window:focus-changed',
  EventImportProgress: 'import:progress',
  EventImportToast: 'import:toast',
  EventMenuExportBibtex: 'menu:export-bibtex',
  EventMenuImportZotero: 'menu:import-zotero',
  EventMenuImportMendeley: 'menu:import-mendeley',
  EventMenuImportIdentifier: 'menu:import-identifier',
  EventLibraryScanning: 'library:scanning',
  EventLibrarySwitched: 'library:switched',
  EventSyncAuthConfirmation: 'sync:auth-confirmation',
  EventAiSummaryUpdated: 'ai:summary:updated',
  EventAiSummaryError: 'ai:summary:error',
  EventAiChatToken: 'ai:chat:token',
  EventAiChatReasoning: 'ai:chat:reasoning',
  EventAiChatDone: 'ai:chat:done',
  EventAiChatError: 'ai:chat:error',
  EventAiChatTrace: 'ai:chat:trace',
  EventAiChatInterrupted: 'ai:chat:interrupted',
  EventAiChatRunStatus: 'ai:chat:runStatus',
  EventAiChatTitleUpdated: 'ai:chat:titleUpdated',
  EventAiReportCreated: 'ai:report:created',
  EventWorkspaceItemsChanged: 'workspace:items:changed',
  EventMineruInstallProgress: 'mineru:installProgress',
  EventOcrProgress: 'ocr:progress',
  EventOcrCompleted: 'ocr:completed',
  EventOcrError: 'ocr:error'
} as const

export const SERVER_IPC_CHANNELS = [
  IpcChannel.AgentProfilesCreate,
  IpcChannel.AgentProfilesDelete,
  IpcChannel.AgentProfilesList,
  IpcChannel.AgentProfilesListModels,
  IpcChannel.AgentProfilesScanRuntimes,
  IpcChannel.AgentProfilesTest,
  IpcChannel.AgentProfilesUpdate,
  IpcChannel.AiChatCancel,
  IpcChannel.AiChatDeleteThread,
  IpcChannel.AiChatHistory,
  IpcChannel.AiChatPendingInterrupt,
  IpcChannel.AiChatRenameThread,
  IpcChannel.AiChatResume,
  IpcChannel.AiChatRun,
  IpcChannel.AiChatSend,
  IpcChannel.AiChatThreads,
  IpcChannel.AiChatTraces,
  IpcChannel.AiDocTextGet,
  IpcChannel.AiProvidersCreate,
  IpcChannel.AiProvidersDelete,
  IpcChannel.AiProvidersList,
  IpcChannel.AiProvidersListModels,
  IpcChannel.AiProvidersTest,
  IpcChannel.AiProvidersUpdate,
  IpcChannel.AiReportsDelete,
  IpcChannel.AiReportsList,
  IpcChannel.AiReportsUpdate,
  IpcChannel.AiSummarize,
  IpcChannel.AiSummaryGet,
  IpcChannel.AiUsageStats,
  IpcChannel.AiWorkspaceMemoriesList,
  IpcChannel.AiWorkspaceMemoryDelete,
  IpcChannel.AiWorkspaceMemoryUpdate,
  IpcChannel.AppearanceSetThemeSource,
  IpcChannel.Bootstrap,
  IpcChannel.CategoriesAssign,
  IpcChannel.CategoriesCreate,
  IpcChannel.CategoriesDelete,
  IpcChannel.CategoriesList,
  IpcChannel.CategoriesRename,
  IpcChannel.CategoriesUnassign,
  IpcChannel.ClipboardCopyMarkdown,
  IpcChannel.ClipboardCopyWorkspaceAsset,
  IpcChannel.ClipboardWriteText,
  IpcChannel.DialogOpenDirectory,
  IpcChannel.DocumentsBulkCategorize,
  IpcChannel.DocumentsBulkDelete,
  IpcChannel.DocumentsBulkRefreshMetadata,
  IpcChannel.DocumentsCount,
  IpcChannel.DocumentsDelete,
  IpcChannel.DocumentsGet,
  IpcChannel.DocumentsList,
  IpcChannel.DocumentsOpenInFinder,
  IpcChannel.DocumentsOpenPdf,
  IpcChannel.DocumentsPdfAnnotationsGet,
  IpcChannel.DocumentsPdfAnnotationsSet,
  IpcChannel.DocumentsReadPdfRange,
  IpcChannel.DocumentsRefreshMetadata,
  IpcChannel.DocumentsRelocateFile,
  IpcChannel.DocumentsRestoreFile,
  IpcChannel.DocumentsSearch,
  IpcChannel.DocumentsSetStarred,
  IpcChannel.DocumentsUpdate,
  IpcChannel.ExportBibtexString,
  IpcChannel.ExportToBibtex,
  IpcChannel.ExportToJson,
  IpcChannel.FileAuthorizeDropped,
  IpcChannel.GlobalSearch,
  IpcChannel.ImportAddFiles,
  IpcChannel.ImportAddFolder,
  IpcChannel.ImportFromIdentifier,
  IpcChannel.ImportFromJson,
  IpcChannel.ImportFromMendeley,
  IpcChannel.ImportFromZotero,
  IpcChannel.LibrarySwitch,
  IpcChannel.MineruCancelInstall,
  IpcChannel.MineruChooseInstallRoot,
  IpcChannel.MineruInstall,
  IpcChannel.MineruStatus,
  IpcChannel.MineruUninstall,
  IpcChannel.OcrCancel,
  IpcChannel.OcrGetState,
  IpcChannel.OcrReadMarkdown,
  IpcChannel.OcrStart,
  IpcChannel.SettingsGet,
  IpcChannel.SettingsSet,
  IpcChannel.WatchAdd,
  IpcChannel.WatchList,
  IpcChannel.WatchRemove,
  IpcChannel.WatchToggle,
  IpcChannel.WebSearchConfigGet,
  IpcChannel.WebSearchConfigUpdate,
  IpcChannel.WebSearchTest,
  IpcChannel.WorkspaceAssetsAddFiles,
  IpcChannel.WorkspaceAssetsDelete,
  IpcChannel.WorkspaceAssetsList,
  IpcChannel.WorkspaceAssetsOpen,
  IpcChannel.WorkspaceAssetsReveal,
  IpcChannel.WorkspaceAssetsTextPreview,
  IpcChannel.WorkspaceCanvasGet,
  IpcChannel.WorkspaceCanvasUpdate,
  IpcChannel.WorkspaceConnectionsCreate,
  IpcChannel.WorkspaceConnectionsDelete,
  IpcChannel.WorkspaceConnectionsList,
  IpcChannel.WorkspaceFilesAdd,
  IpcChannel.WorkspaceItemsAdd,
  IpcChannel.WorkspaceItemsList,
  IpcChannel.WorkspaceItemsMove,
  IpcChannel.WorkspaceItemsRemove,
  IpcChannel.WorkspaceItemsReorder,
  IpcChannel.WorkspaceItemsResize,
  IpcChannel.WorkspaceNotesCreate,
  IpcChannel.WorkspaceNotesDelete,
  IpcChannel.WorkspaceNotesList,
  IpcChannel.WorkspaceNotesUpdate,
  IpcChannel.WorkspacesCreate,
  IpcChannel.WorkspacesDelete,
  IpcChannel.WorkspacesList,
  IpcChannel.WorkspacesOpenSandbox,
  IpcChannel.WorkspacesRename
] as const
