export default {
  "addFile": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAC+SURBVDiNpdI9bgIxEIbhh58CUVCloIOSY6SGJmXKkJNwCZQIpCiXiMQNkhNQpKJOjxA0m8YIa1njXfFKI401ns/zY+6kFfkPeEW/4t4f3lCUA+3In2OaeGiJVenBKxbBqijwhXVZpJ1IqOIJI3zGIt2ayUecovM33psI9CJ/geH5kGthEixJTuA5WJJbLezC0OAF46YCY5e1ptabHeImE88K/DQR2GPmRrmBx/ArQScK/GJQo6otPnDIVVeLf6tGGIFtzmH/AAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAC5SURBVFiF7ZZBCgIxDEUf4h1ceK25r3TtUiyDMngQRd2kC6HKTH4GZrAfQiltk9cmlEDTQtUBGXhNtCOwiwA4O4IXGyIgijPPmRAIBeBm40WBUAD29gLSSygAWFAJQgUoEL0XQi3Cmp3mBjiMgJgVwOVvExjEpdUDJMt9uMbWgLxvlSlIlRuV+eR0eACeP9YeDn9V/U8NbMXzCbgHsXyofcUNINvobc1rfUD+EquqDrgGAvTms2l5egPqdJs3cXMcHgAAAABJRU5ErkJggg=="
    }
  ],
  "paste": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACSSURBVDiN7dMxCsJAEIXhj5jCyjNYWOgtxE68lF0K7+AtchUFT2CnjRFRiM0GlpiVIAgW/jCwu/N4zMBbvkSODY6hCgy6hFl0XqJCjTvGWISa4BF6VdC+sA4FZ0yj3gynDp08scIQ+9bbLbVryqAXWQ/N3+DnDeIcXLASpSzBHGVziT/IAaM34WrYYYvrRyO3eQJIXRZgoR7vggAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADGSURBVFiF7ZcxCsJAEEVfrC00pwnkGrmE4OU0aiViqQfIItjrBcQ2NiMEdYcdicFiPgyB3fl/3m6aBFx2ZcAcqIErcAGWwGyI4VNgB7SR2gB5H4MqICiDFkAJTKRKYKX0B8lMVqOE1YpvrfgaC8DT1NVR1grFV0jPISHPDHCXtbHiy6XnlgqQKQCv+6YTRLxv80aGwL2hd2vo/SjzO/s2z3IDP5EDOIADOIADOIAD/C1AkGfsC9da3cwkVcC5R4CT9b/ANZgeeWVrYNVCYmIAAAAASUVORK5CYII="
    }
  ],
  "sticky": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACsSURBVDiNzdIxCsJAEAXQpxDSCBYWnsMqlZ3XUURvoLdIb+cRvIG9So5ikNisIMmuxEo/bLN//mdm/vBPGGCNK2o0rVfjgmXKYIsbFsgjfB64G1YxgwpFj06L0EkHNbIeBhnuMaLpIe7UDr8QRdHHYBCW9p7OVyNsWukcUcYKU0t8T2cfEhjHDCrMIv+PYLwLY0xTs25xwrx1SA0OOGOSEkss63XCJUafxL/DE5P8KqOS5o8sAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAFfSURBVFiF7Za7SsRAGIU/xU6UCGJhIT6Ddlt6QV0bOx9AsLHQF1BWbFLoa4hoJ4o38BXstBPE2y5oJXZKbM5AWGLyT0wamQPDLjPnP+fszCT/QkBAPiJgG7gAOkBiHB3VtICBsuYLQNvD9LfxDMyUMXcCx8CkdsOKSDUnKZ05a/EQ8Kqi2Dd5BnZTOzFoKdhQwXUF5gA9wJU01ywFRyJPVxQAYF6a+xbyo8g+Z16EUWk+WMju0lSNTN3eGoy8EAL8uwB5vcOMsk/BIvBS0Bdu6gqQ1zsi4ElrzToCFPWOU62dWwV9A6yLf5ax5hrROzBuFXS/ZsTIPxR/qmt+U/OfwITVHG1VAswa+W8ZvWNLc9/Wc08jVvGlkd99ZHFqbsXXHJ3VhwT2gD5jgH7gQN+/gOUy5g5LKeFbYBUYKwhwp8820PiLuUPT859wogs5XIW5QwTs6D7khbnXmzAgwBs/Qp2cacJMvu0AAAAASUVORK5CYII="
    }
  ],
  "note": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACySURBVDiNvdIxDkFREAXQE7EZka+TKESjEZUlWMXXKhQa67AFhYQ9aPSE0g7QPPLC9z0hbjLJTN7MvXcmjz+jFqIQK1wKYhjeM+yxC/kTLiXKGU7I0Q1Edagk2M6wwAwjNHFOddDAEb1Q58FJI4WgjkM03I6tvyOoPSh3wvFuyoN3BGNMo+H9w+XvvWVHbGGCOfrYFDVVXwwvoryLbYlQ4QrJvSn/oBTxCusPXCy/Ff4drjEaKEQw2Th1AAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAEESURBVFiF7ZZJCsJAEEUf3kHisPFQ3taFuFZwE6NxvoluKlA2GapiN4jkQyNUm3qP6kYDQ/44GbADtsDE8+ASKICXca0b4Gf1nbNH4uCAv4BV8PxUwW/AXUlMLQJV4z7JBFoBZ8Bc1S6WSfQVCMeeSw2BHqW+TyGgx/5UYy9lb5ZSIAvgCxn7RWpXqZvvgUdAn/lD4HrvpPrd1JFEEWiDA4zV2M1wq0AyuEUgKbxLIDm8S6AIbnsIz1tu+6bhZ9slUO154V193QIh3DL2JAKeM48qEC7LhYsisK6Bl8a/2SgC36S27ygByJVB4CcFCvn0vJhalu7dmqV6m4m5TtJ7yJCPvAEf8dlY12QXPQAAAABJRU5ErkJggg=="
    }
  ],
  "copy": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABDSURBVDiNY2AYrOAFAwPDfzz4BSED/hMrz0SpU5ENQHY2A02dTTMvDIwBLCSqh/n9J7kGMKILUNULPwlE5U88cgMIAOqqGpG+pSrVAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACFSURBVFiF7ZVBDoAgDASr8f8vIkFehicSxZaUUtTEnYQLh3VpRiACQE8iojy4Yh26dBTITge5fHMbDeiAPcBqDHMDBbgCUTC4YLJdghNqiu2nXPVf4Gq7xCcdQAEU+FcBy2uoRXUfPD2BUG/MnIDqJn3dARRoOeD1LDfhJrA75N5sB0DiAKaiKk5HeiDGAAAAAElFTkSuQmCC"
    }
  ],
  "edit": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAC7SURBVDiNzdBBagJBEEbhLzoavUQu4AnUGyhZegVPF4miwYUEFx7CS0gigugioJsKDDLtaNzkh1500a+q+vFgqje+e8YQe2zuHVLHHCts0f4LPEOGPr7QuRX+wDfeUYt6Dzu0oHIFHoejl9y9hk+s0YWnBPyGJl5xDHAUDas4YICf1NqLMJ9PMyROwkdS2LIAzkLkPAWLFYsmZyFxFkOSOaFRAE8wLYN/G6TWLoUvG9wNC3mn3Cn98//IGd+5KNyaKfmrAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAE8SURBVFiF7ZVLSgNBEIY/UETE5QyJTMBgFh7ClXfwQjmHh4jiwpUrNzlAHoNxjGACgbjICRw3NVA0o9NMd4/E5IeC6Qf1/V1QNbDXP9M5MAA+gVvgtEl4B5gDuYohcNI0PAWugLWsn4HjJuGR7F8CK9l/Ao6ahBe6UCYegcNQ8J8MmCbugQMf8DbwKknflZEJ0Cq53wOWcqfvCj8DZpLsA+gCiTKUikFT13K+calCW8EX0veFEiCTs8yoRCKVyoG7EPBCLcNEYsCnQFwXnkqSpZTd5m4GvMn32AVe9XJTkTLh9PK4Btw04ASfbjN89tfwsllgpQc1ZGzhsUzBHHhxgQN8SaLfWk0rAka+4KjWsYV7KXsdA0HgtgY0fO4TbmPAhHd8wqsMBIcjP428IoLBAW7U/C+LSUj4Xrunbw3Lm7TNZBhKAAAAAElFTkSuQmCC"
    }
  ],
  "export": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACxSURBVDiNtdIxDkFREAXQQ+iVOqXkR5RESalT2INlWIY10IpEIXqlHVBZgZZmvrzEl/9J3ORlXu7k3jfzZvgzFnE+olFi0C57of51TRUMusgK+CxypQYNbDFMuFFwZS2/0MMFexxwDe4NtYhTDOJ+wwp9HIMb4xwTyT/2hF3ewiYxbUU8Y5KI0xys00oeFVvroFmkqWpwSxbrJ4O3CvKx3LGsaJLjLtmD+ZdimP2g+QOenOAbT+KAJdsAAAAASUVORK5CYII="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAEBSURBVFiF7ZVNCsIwEEaf4sYDiNQuPIqXcOfWW7rQulXRhRT/qm48R9xMJcZEqk0QIR+EgWQ630tKJhBVTxkw/SWAkvG1mv5YIkAECAfQAObAAuhWyE+BJTDzwPcAWMt1OwE9bc28hilwkbmVLwBk54UUvoqRCZDKmpLcKqdVG6IE6Ic21yGOYnTWAG4SDyHNdYhCM1e+dj4EckthZXlwEu0kyp0nRk7mqJWL14u2jg8UMLHkJ8Ae2FnMEWhXva0NoPbLVlFPPn/RCb9VBxhLrCTfv2Aj9TbvfEKeQNuIVrUCAoyAwSePUrwFuURX8/A1dK8nDY32GmrsXK04KuonugMon5K4UQ34XgAAAABJRU5ErkJggg=="
    }
  ],
  "delete": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABeSURBVDiNY2CgEShkYGD4xMDA8B+KP0HFiAZfGBgYJJD4ElAxvOABko2E8ANchvwnwnUoapiI0IAX4DPgAg42XvCfRDZtvUCxAR9xsPEC+kcjCxr/ABGu2EOppdQFALXPIJgisKrJAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACsSURBVFiF7ZZRCoMwDIY/hofwNPMSntAnbyFeQga7gDDYBRTcS/YiTWhLO3DkhyCEv8nXtGDBFa8WGIAVOJRYxdPWABiNxucYawC8pfjd8HTiedUA+O6ulA+AWyA3KWM9N9DC8k0xADW1p5iTRplb59cTcIAiAHPoNhv5bGmXp1QernoEDuAA/wXQZKyZgS0hny3/GzrAIt/Yp7j1RlyMPqp64FkA4CG1XK6gPnoQa7IwmZzVAAAAAElFTkSuQmCC"
    }
  ],
  "remove": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABeSURBVDiNY2CgEShkYGD4xMDA8B+KP0HFiAZfGBgYJJD4ElAxvOABko2E8ANchvwnwnUoapiI0IAX4DPgAg42XvCfRDZtvUCxAR9xsPEC+kcjCxr/ABGu2EOppdQFALXPIJgisKrJAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACsSURBVFiF7ZZRCoMwDIY/hofwNPMSntAnbyFeQga7gDDYBRTcS/YiTWhLO3DkhyCEv8nXtGDBFa8WGIAVOJRYxdPWABiNxucYawC8pfjd8HTiedUA+O6ulA+AWyA3KWM9N9DC8k0xADW1p5iTRplb59cTcIAiAHPoNhv5bGmXp1QernoEDuAA/wXQZKyZgS0hny3/GzrAIt/Yp7j1RlyMPqp64FkA4CG1XK6gPnoQa7IwmZzVAAAAAElFTkSuQmCC"
    }
  ],
  "ai": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAD0SURBVDiNndLPKkVRGAXwnz/nGdSJpAyMjAyUqVdQhsyMzMTQI9yBKyXJK0jhAZSBASYyckdKdDOkhMmn9jntwz1Wrc6391rf+vY+bQbHTLCC4RYBy8F/oYevYG/QphMcJ+vtYAWjDc1zmEjqK5wl+lp894YaAnbwgBGMYz3RVnAY9WquucALymh+jqAUW8HKVRbRicn7iXYQe53wZK99jztsxOQ6SmyG5zYVft5BP1l/ZAI+k7qf0RVYwnkEdBNtN/ZOw1PkAlJM4S2OXUY92WSu/114xTTGMIsnHP01tY4FXOMG878Zm17iBR7xjsu201vhG1RaLah0NrcsAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAHtSURBVFiF7ZbJShxRFIa/BJMQjRAwiJjGJwjZRskriNr2SnDCdbvL8BQ+gFmIgmThRhBcdeOA7cYGiUlWWRvBARQUmpiQyuYvOBa32nt7EoI/NNw641/3DF3wn2Ib2LxLApF+t+Jh87m0jsC2483j59RyNJLA3yq6Pw3MwyjwEzgBRlJsvHsgFI+AM5PgVLKWEcgq8BfgQOecw24LKDjkdY/nqpK+Az7ovBbgX9fNdAHXCtALvNT5t3TVYCfkxmSETMGY6l0AjtSIG0CbdNXgmpDgySiL+ZSRzUhW9oxRcwkG5FgBnhl5p2SRbG5DWnM60Q5MAyXD/LPDbsXod+Tz1DeJC/3AJ+DKBK4Ai2q+JDLAkrmJCLgE5oE3IYlfm9mO1DgFYALo8PDvkG1RvpHZGa98CPyQw1fgPdATwj6BHu2Jb4r5Pc3QjqHPW4bAdnunj8OgYRyXoAiMB5Rg3FGCXx574gbSmnAB6HbYZ9SglcSmKwF54EVIcot4DHdN0DmH3bLRHwAfgb5ak6YhXkTHib6xi+hto5MmEa/iYSObkmyv2ckBZpVs1ciKkuVbQeC5/sGude5Wt8fPNaEtwPYCWAeGgEngCfBAsotaCYQipyvfN2s726rkAI+BczN2ZykfpU1FTp/khyrHPerCP5FhoKcmbPlaAAAAAElFTkSuQmCC"
    }
  ],
  "file": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACpSURBVDiN1dI/DkFBEMfxjz+FKFQKnauoaRzhcRKXEEIiLuEMbqBwBL0IzdOsZPPsJg+VbzLJTGb2NzOb4Ucakd/HHN1E3QUrlNVEM/JnGGcaLbGpNHxjESxFiQO2VZFm5kGKKYbYxyLtmo/veETxEetPBDqRv8DgFXyyQpKcQBE+LrYiVZhbYR/sjyeoTTzBFRP5a3wxClcJWlHijF6N2zhhh9tXI1d5AkEdH1YA4uanAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAClSURBVFiF7dYxCoAwDAXQj5dw8Fretzg7iqUo4kVEXdKtQpukopAPpUtNHiVCActH0wPwAK7CNQJoNQAzo3lcmwYiFuN8o4KQAHbaFwlCAujoBkQ3IQGAmooQUkBEBC5COoSpNdUGuAxEVQCrXqPYhBUDlAKGjEFzNQFnxpmjsGYy9hc8xWZAvd7vZsAArwE87dyneeod4B96JdMDWBUBgWpavpcb572fcQr/qTgAAAAASUVORK5CYII="
    }
  ],
  "open": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAB0SURBVDiNY2AYKuABAwPDfyT8glyDbBgYGN5ADcEA+9Fs+Q+1GQYsGRgYXjEwMDjhMgCrIBQYQZ1tgU8tLgOMGBgYHjIwMJggiX0gxYBTDAwMenhcR9AAZHCBUgMw1DARoQkvGHgDWJDYB4gIhz2UWkh9AABjFh27cfN+QQAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADJSURBVFiF7ZZBDoIwEEWfnsFEjR7GQ3BbF8rajQuDRDF6EnEzi4bQ0imFuJiXNITQmf9CSSkYRj5KoB0Yp27RMqPAN2LOIWNeFCug7ryFWcMrCX1rBAqnUL2mnvC9RuAWGd4Cx576DXCX5x8JRyMwZq3WwMsJ36X0TRUIhU8uMBQ+qcAWaKSmkfs+zp5vZpTAArjK/EcgXIVW4CKbTZZwrUCIMrBPzCIQ1SfnzygJEzABE/hLgUqusYcS33B7qSiAZwaBWnoZRpAf362Cpie1T9EAAAAASUVORK5CYII="
    }
  ],
  "reveal": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADTSURBVDiN3dExS4JRGAXgRxNBpKCtwT8g/QAHf0EGbS1Bg03ugrNjODkL9gMi/AnR1BKtBQ3NDW3Chyhoy73w8RF9d2nxwOXlfXnP4Zz3sjc4Q4Zd7t3juIxYC7WDCcahr+IWb5gFwYgMd/iOi79hixEGBTL00C86iDjBDeolzs+xwqwoMMUan3+Qn0K9xiYK7NAIx2xhWeIArvCSv8EFHhPJpyHmaxSooI2HBDJcYpEfjEP2w0SBD3QVfuELwwRyE0d4hoMwXCVmhw3meE/c/2f8ACahJ71ItXYpAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAEeSURBVFiF7ZWxSgNBEIY/DUJewTJdMEkZ0krS2AgWCeRtYq2xjNqk0i6+Q55BSECEFClVTBHsVGIzCytk57Iwm2p/GOZumZ3/Y3aPg6ysrP/qAi/AJhDfwCNwnApgrpj7sQIuUgA4g5DKwNiru5e1vQE49YGvHae1kWPtWgIAVIDnCIiZNUCMgn0PE5hFqQhgFHnWoXBy7wvgfJuhv+HUwFiLt6IJ9CXfAAeGcSJ9f7QJlIBPeW4VHFOsLqXvgwbQlrw0Ngd4ld7qHbiTPDQ2r0nfNXCkAbxLbhoDDKTvOFTg39KU4z/bBeDa2Lzu/UlLblH7DCfGAD3JT8BvqGgf4+9oRQ7gyti8sW38GkCquC0inSY0/wCqpnPNyrLQHz0zy00qoFejAAAAAElFTkSuQmCC"
    }
  ]
}
