export default {
  "undo": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADFSURBVDiNzdK/SoJRGMfxTy4uodGoeAdCg+EduIabk04O3YLeRnfQpggGQkgt0tDgohfQ0CIogYtLhGDLIUL0ff0D4nc5w3N+3/McnodzpYoe5vhAG7WowDicWbygiwLSuMIt+hjgepNgFQIzNLc8coEHDJHcJFigEvO1BN5wv174DpIVPmMkd3iPuRNJDl//W9qXHyyPEeQxOiD3xyvK24pplCLCDTxH2VNohc0rBuElbvAYRpjZpc0yOphgiifUdwmenl8QZiJnsfeHUAAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAG4SURBVFiF7da7axRhFAXw3+6ChRgigmIhChpEC0XBFNY+QbBTgv4BYsBKLHyAhSnFUiysFWwUbBQLk0JEQQmmSBEQUgQEsROMJmFt7sCXYVjnkewW5sDHHWbmnnPunflmLhsYMDoN8vbgIIawhN9r7K0Qp/EMi+jm1gzGMbwewifxqUC0aP3CvehMJbyNlceVhHwZz3EHZ7EdO3AOd/Eyufc7rlYxkCWmuJmc/4rREjyjmE7yJuoYaOFBcu4hNlcopo3r+BP541UMtPE0afmFCsJ53A6eldg1pQy8iPgTpxqIi2LeB9/jsga6+IEjDcUz7IudsfSvLvTaWkW7owqeBM+1/IV2cjzZg2C5oYHPEQ805KmNE9GBXkWuK7aFgW/5C+3i+9ccWyNuGZSBQxEH1oHDEb8MykDWgTd90luF3fEh6mKk3+ItvAvxV/0WhxshvohddQjGYrCYwKYKeZ2YilbCwKU64nAx+R/M4XiJnL34kOTdqiue4XJMvBnhLB5FVTtjCD2P+/gYf71sNmwyS6zC0XiJygylXUxhfxniVkUjx3AmHsVIvFgdLGA+OjCJ1/Xq3MD/iL9K2ofQtFunagAAAABJRU5ErkJggg=="
    }
  ],
  "redo": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADJSURBVDiNzdIxTgJBFMbxnxgtIMTEws7S2mIJVzAU3sDWmHgACwqO4BWolRY6tDE2VBtPoBYmlhsSYrc0QwILmwEMCf9kqnnfN9+b99hHqujgEzkyvOMB9Zj4At8YIMFJOAn6+MB5qE2L4mN84REHJQ+08YtGSLfAHV5RiaS8wXiVwQtaEfHsX3L8FS8nOIsYLFGMW9b7WgYpmpsazHOP0X8MjvAWRlXGVWyZ6hiii0vUwiI18YwnnMaSHOI2jDXDD3q43qqvnTMFFMwh0uAE46sAAAAASUVORK5CYII="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAGXSURBVFiF7dY/SFVhHMbxT04R4pQX1CF0igZzCULRIYLAPxCEdCGaWl2sKQgcagrUUYQaanGVCFoCEQQzjEYtShwCF1FBC1q6Lu+BF7ldzz3n4B28DxxeOOf3vM/3Pee8Lz+aOu+6kMFzH2VcRRcq2MBPfMUrHBQNehHPcRgCa12/MYvLRYXfxnYU8A5TGEEJ7RjGMyxGdTsYrDLfMpbSht+NJlxHbwrPTWxFvscnnif3T9VIVDyRljioFa8j/0y9AB3hW1bwtM7wWONR4EI9AG9C0UqO8ER3osUspgHoif7mKwUAwA3sndgt/9WTUPA2Z+jyKdsVtFQx3gvjl5wA/2o8+1jLeBQIh3ICZFbyilrPIqzaJ0h0qVEA38LY1yiAz40GWAvj9bMAqKYO/Am7oaiDqG5NR0dxlqYlt0rYDxCTjQCA/uhMmMrgf4FdPMoD8TCC+ITuFJ4BfI985TwAMBZWkky4hpcYRRs68QDz2Izq/oZ+oBCVMJeyKa3gfcr2LdMfXsYtXIvOil/4gVV8CO15U02l0jGVB4Jot4/bMwAAAABJRU5ErkJggg=="
    }
  ],
  "cut": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADrSURBVDiNzdG9LkRRFAXgL2REaIgMCTIeQEKn1/gpbqdRTklBFJ5AqRKZRiWU4hlIDK1EoSAqFH4iHsCIZkuum5tzo2I1Z2edvdZZex/+Gt25uoEm6rj5rcEo2njGMiZwktDVsYqLb2IN21EP4SUhXsA9VvLkPM5QQ4Y3jBWEvdjBNabKnFvo4B3HcS7lIt9iFz2pnRSjPuAQA5gua+qqMPlEH67CJIkWPnCOIzxhNu5mcBeLrpWJF3Ear8zFEkcKPf3YwyUmiwYb2I96EK+JpBkesZ4nx+PvN3GArYpxh2PkH2hEkqxC/M/wBWJLKOQyxdt0AAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAICSURBVFiF7dbPi41hFAfwj5kxRjEmZUMWpEzKTpqYBSWSFVGUopSQjYXFlSYsrSwsLJSVHyml5D8YzRBRfmyMshhjRmFiSBjXwnnr6XbfmTvvnYvF/dbt6f2ec55znvOcc55LE038h5iDEvrxKdZS8A1HG66hjJ94EmsZ10NeL7rQmSc8FM6GsTq4brwJ/nCdzvdjHI/zFO6Ho71VDMt4UNDxEtyOPco4lac4hokqqW7Dt5DPFLvwIRyPYvNUygOhuK+CzzIwMAPHXUk9lXEruClRSmqgO7g1SQ0MY10NzrfjbdhM4GCtUbdgsKILfsT3WMKfyemIdlxJTj2IFbU6z7AAffiISQzhLFpxDF9j84dJljJkXTSJc2Ez61iVdMt3nEyG1DJ/stPTCMcpWiNL2fX0Y3mRjVpmKaCNeB5X0HCsTNq1jAu4mHzfjcFTGJ2R3vEoppdJQR1NinAIvYndFoyE7D12F3HehkfJadLfaKy/cB4dVewX4XJic7WW4ZOiLwyfYS3mYSdeJYNofQ377EgCHsHWWgPITt9bwfcUeIwWV4ziS5g/ndGXUG6v4BcG/3kGAWTYkzxGr7FhKuUXobitgt8U/NMCAYiuuJPU0Ik8xeOh9C7uviPW7DE6UjCADAeiu4byFObiZk4X3Ah5vVg6XWe04DTu/Ys/pU008dfxG5ufnpvxyN8XAAAAAElFTkSuQmCC"
    }
  ],
  "copy": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABDSURBVDiNY2AYrOAFAwPDfzz4BSED/hMrz0SpU5ENQHY2A02dTTMvDIwBLCSqh/n9J7kGMKILUNULPwlE5U88cgMIAOqqGpG+pSrVAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACFSURBVFiF7ZVBDoAgDASr8f8vIkFehicSxZaUUtTEnYQLh3VpRiACQE8iojy4Yh26dBTITge5fHMbDeiAPcBqDHMDBbgCUTC4YLJdghNqiu2nXPVf4Gq7xCcdQAEU+FcBy2uoRXUfPD2BUG/MnIDqJn3dARRoOeD1LDfhJrA75N5sB0DiAKaiKk5HeiDGAAAAAElFTkSuQmCC"
    }
  ],
  "paste": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACSSURBVDiN7dMxCsJAEIXhj5jCyjNYWOgtxE68lF0K7+AtchUFT2CnjRFRiM0GlpiVIAgW/jCwu/N4zMBbvkSODY6hCgy6hFl0XqJCjTvGWISa4BF6VdC+sA4FZ0yj3gynDp08scIQ+9bbLbVryqAXWQ/N3+DnDeIcXLASpSzBHGVziT/IAaM34WrYYYvrRyO3eQJIXRZgoR7vggAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADGSURBVFiF7ZcxCsJAEEVfrC00pwnkGrmE4OU0aiViqQfIItjrBcQ2NiMEdYcdicFiPgyB3fl/3m6aBFx2ZcAcqIErcAGWwGyI4VNgB7SR2gB5H4MqICiDFkAJTKRKYKX0B8lMVqOE1YpvrfgaC8DT1NVR1grFV0jPISHPDHCXtbHiy6XnlgqQKQCv+6YTRLxv80aGwL2hd2vo/SjzO/s2z3IDP5EDOIADOIADOIAD/C1AkGfsC9da3cwkVcC5R4CT9b/ANZgeeWVrYNVCYmIAAAAASUVORK5CYII="
    }
  ],
  "selectAll": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACmSURBVDiNzZKxDQIxDEUfJwZgDMbICJRXsgIbZBw6KE+iICNQUrICE4TmE/mCD5STTuI3ju1n5ysK/JOuQAYeyvfKs86ol8V+KDdcVti1KT4Vt0A/MXgE7oalM82NYg8EZziYxW925GAHnHVOQKwWRI+1Dk4Ttj0VtvvO/ZZdcGiYK+zKaUY9WKrqwXsb6+CmODjDqDZU7EizPpJ1kBq+8qXhsoX1AhDJJsUnnjH4AAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADNSURBVFiF7ZbhCcIwEIU/xWW6hOAO7qODCW1msAR3UdQ/Eex5mGtz2IL5oJRc08cjub4GKpVP9kAEHm9XK+YE8dwyJybtAWvFwBFoRO0mxnflvdycJmlneTn2RtXVVuCnzG5go9QCcFVq25HaHbDL6LIyik3tiay+tgJFggmz4dl7QDPQKqHiQbDqat/r2GwwayxyC/7LgDWIPCjS9WhClUVuwTfcf9PWIOomaJ/EuCiIPKhBZDYQ0937VAzQWwwcgIuoeZyKz0m7UhnwBAjKUU7bS0/bAAAAAElFTkSuQmCC"
    }
  ],
  "add": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABJSURBVDiNY2AY7CADinECFgIGSBCygYlkNw06AxiR2BlY/OwApQ+gib9gYGCYge4CARIsJlptAxTjBAMfiBQbQCgl/qDUAtoDAB+dBhikYyuiAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABZSURBVFiF7dXBCgARFEbhP3n/V5LnGsWGUhYzcaPJOWWHviwuiWitKCmcBOS6pnN2FgAAAACwA4Ruwr2t1tf9w9je/QLJ+kL+AgAAAPwf4BfPR0mPkYUurQCvKB3LP8vkiAAAAABJRU5ErkJggg=="
    }
  ],
  "addFile": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAC+SURBVDiNpdI9bgIxEIbhh58CUVCloIOSY6SGJmXKkJNwCZQIpCiXiMQNkhNQpKJOjxA0m8YIa1njXfFKI401ns/zY+6kFfkPeEW/4t4f3lCUA+3In2OaeGiJVenBKxbBqijwhXVZpJ1IqOIJI3zGIt2ayUecovM33psI9CJ/geH5kGthEixJTuA5WJJbLezC0OAF46YCY5e1ptabHeImE88K/DQR2GPmRrmBx/ArQScK/GJQo6otPnDIVVeLf6tGGIFtzmH/AAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAC5SURBVFiF7ZZBCgIxDEUf4h1ceK25r3TtUiyDMngQRd2kC6HKTH4GZrAfQiltk9cmlEDTQtUBGXhNtCOwiwA4O4IXGyIgijPPmRAIBeBm40WBUAD29gLSSygAWFAJQgUoEL0XQi3Cmp3mBjiMgJgVwOVvExjEpdUDJMt9uMbWgLxvlSlIlRuV+eR0eACeP9YeDn9V/U8NbMXzCbgHsXyofcUNINvobc1rfUD+EquqDrgGAvTms2l5egPqdJs3cXMcHgAAAABJRU5ErkJggg=="
    }
  ],
  "addFolder": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACwSURBVDiNxdI9CgJBDIbhx79GQSw8kFh6AlutPIalIFhbeQdBW7GysrAUz2C9laBNhEXc3WnEF4ZMQubjCxn+TS1iH1O0I39ii0uVQD3iBKNcvYUDhlUCzYidj/oDZ+ywijxPhg3uTcWc4nxjFGMu8wJHzKssB/O363pF4yxOIWUjzDDO5etvTWUOegX3ZAeLgnuyQOnDT4EsVpO6hQH20IjCDd0ER2+u8ZGyxP4f8gI2vBqA/+bEqQAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAC3SURBVFiF7ZZRCsIwEAUH8QSC4J+XEgQv6REkh9AqCr2HivVnC1pN1bRPW9yBpYSk2UmypAXH6RgzYAMUkTgCS2CqEljXJL+NHJgoBMoEMcZAZmP21v6qQFUiA0YKAVVsrc5+JlBYnb0UUPEw/0CY7C16LxCAVUsukFADjcf38gjCk5WU7Y+PI0XgUtN3Tpjvjv+rgWHD9wNwaskF/CrugsDOnqpPMfYTE2UBHIQCOTDX7KXjJHIFO6Se0cZlklkAAAAASUVORK5CYII="
    }
  ],
  "workspace": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACTSURBVDiN7dEtDsJgEIThh18BCQpPr4DAFwGGW2C5BCfhLFVoDBUoDoAGQUIwK5ovbRCQ1DBq581ms7NL2+pU6im2GIW/4xB1Hb9BrzJghw2u4VcYY97Aj+mAdTTtUWCGAYYJz4IV0P32BtUNFrFFhhxLlHgmPMe5LsIFE/TDl3GsUwN/1EV4Jb7zgf+/8IsvtK83DGcxMHYW3GwAAAAASUVORK5CYII="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABmSURBVFiF7ZUxCsAgEASXvNGvG4Q8Jmk0pLmcpxhSzMBh4Sjb6EoAPyVJKpJOY0p1Rn2X/HJZmzzhu7RDvftR/2aLpFoBAQhgBdjraj2ppzPiuyRJR/AjivjgQhfQBQQgAF0A8BkXBYuXxY5XW9cAAAAASUVORK5CYII="
    }
  ],
  "file": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACpSURBVDiN1dI/DkFBEMfxjz+FKFQKnauoaRzhcRKXEEIiLuEMbqBwBL0IzdOsZPPsJg+VbzLJTGb2NzOb4Ucakd/HHN1E3QUrlNVEM/JnGGcaLbGpNHxjESxFiQO2VZFm5kGKKYbYxyLtmo/veETxEetPBDqRv8DgFXyyQpKcQBE+LrYiVZhbYR/sjyeoTTzBFRP5a3wxClcJWlHijF6N2zhhh9tXI1d5AkEdH1YA4uanAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAClSURBVFiF7dYxCoAwDAXQj5dw8Fretzg7iqUo4kVEXdKtQpukopAPpUtNHiVCActH0wPwAK7CNQJoNQAzo3lcmwYiFuN8o4KQAHbaFwlCAujoBkQ3IQGAmooQUkBEBC5COoSpNdUGuAxEVQCrXqPYhBUDlAKGjEFzNQFnxpmjsGYy9hc8xWZAvd7vZsAArwE87dyneeod4B96JdMDWBUBgWpavpcb572fcQr/qTgAAAAASUVORK5CYII="
    }
  ],
  "folder": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACVSURBVDiN7dKxCQJBEIXhz/NMFIwsSAyvC63kcsES7EHQVIyMDAzFGowvEjQZcRFlFQQTf1iGeSyPN8zwa1pRB5igG/0FC+xzBkXUMapE72CNUc6gjNp70M/YYYlZ9CkN5jiVXrON94wqxpymBhvUuchBfUtdZL9m+Bvc76CJ1by7hSFW0A7hiH5imOMQh9R8HPnrXAGYNRaag5RSBgAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACMSURBVFiF7ZZBCsIwEEUfHqEguOulCkIv6Wm0LRVyj27iZgSJpBXhaxf/wScEQuYxDCRgzM7ogBuQK1mAC9CqBK4rxV+TgJNC4FmgxhEY4swc+58KlBID0CgEVBljzv4mkGPONgVUvN1/EBb7CAtYwAIWsIAFSoEpVtVTTHxiqvTAXSiQgLOml8Z8yQMhCIQzrqJXBAAAAABJRU5ErkJggg=="
    }
  ],
  "open": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAB0SURBVDiNY2AYKuABAwPDfyT8glyDbBgYGN5ADcEA+9Fs+Q+1GQYsGRgYXjEwMDjhMgCrIBQYQZ1tgU8tLgOMGBgYHjIwMJggiX0gxYBTDAwMenhcR9AAZHCBUgMw1DARoQkvGHgDWJDYB4gIhz2UWkh9AABjFh27cfN+QQAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADJSURBVFiF7ZZBDoIwEEWfnsFEjR7GQ3BbF8rajQuDRDF6EnEzi4bQ0imFuJiXNITQmf9CSSkYRj5KoB0Yp27RMqPAN2LOIWNeFCug7ryFWcMrCX1rBAqnUL2mnvC9RuAWGd4Cx576DXCX5x8JRyMwZq3WwMsJ36X0TRUIhU8uMBQ+qcAWaKSmkfs+zp5vZpTAArjK/EcgXIVW4CKbTZZwrUCIMrBPzCIQ1SfnzygJEzABE/hLgUqusYcS33B7qSiAZwaBWnoZRpAf362Cpie1T9EAAAAASUVORK5CYII="
    }
  ],
  "reveal": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADTSURBVDiN3dExS4JRGAXgRxNBpKCtwT8g/QAHf0EGbS1Bg03ugrNjODkL9gMi/AnR1BKtBQ3NDW3Chyhoy73w8RF9d2nxwOXlfXnP4Zz3sjc4Q4Zd7t3juIxYC7WDCcahr+IWb5gFwYgMd/iOi79hixEGBTL00C86iDjBDeolzs+xwqwoMMUan3+Qn0K9xiYK7NAIx2xhWeIArvCSv8EFHhPJpyHmaxSooI2HBDJcYpEfjEP2w0SBD3QVfuELwwRyE0d4hoMwXCVmhw3meE/c/2f8ACahJ71ItXYpAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAEeSURBVFiF7ZWxSgNBEIY/DUJewTJdMEkZ0krS2AgWCeRtYq2xjNqk0i6+Q55BSECEFClVTBHsVGIzCytk57Iwm2p/GOZumZ3/Y3aPg6ysrP/qAi/AJhDfwCNwnApgrpj7sQIuUgA4g5DKwNiru5e1vQE49YGvHae1kWPtWgIAVIDnCIiZNUCMgn0PE5hFqQhgFHnWoXBy7wvgfJuhv+HUwFiLt6IJ9CXfAAeGcSJ9f7QJlIBPeW4VHFOsLqXvgwbQlrw0Ngd4ld7qHbiTPDQ2r0nfNXCkAbxLbhoDDKTvOFTg39KU4z/bBeDa2Lzu/UlLblH7DCfGAD3JT8BvqGgf4+9oRQ7gyti8sW38GkCquC0inSY0/wCqpnPNyrLQHz0zy00qoFejAAAAAElFTkSuQmCC"
    }
  ],
  "link": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADiSURBVDiNxdEtT4JRGMbx3yzO4Mv8DGxuNqfgkGhgvmCQYZBgkkLgy1D8JlSDyUJ0s7jZHKBs6ixMyx2eHR8cGPQqZ891nv+5rvsc/lBLKGHlN/ABXtDHB1rzwEcYRDoU8IjarHVr2En2z3H7U91XfGIype5ijPRN9ajbxCpOMM6p28F1Ch9jhO34vsFCwNm6FQyxlYU3Ai5nvAdsxn3chVfEMw7T9B7aideNZ6tgGReRfJo3+zh+ymodV7jHe4xUzoNF0n7iFbE7DUh1hic0sBZ1B6jOegBcRs23WPfmgf9PX8tnK2lwpDArAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAIHSURBVFiF7dY7aBVREAbgz2uigkTiK0FBsbCUGJugEjVgl8JGFG21ESQStBErsRAsLFWsrHzEBwHxWfgkoIWlCFYG0cKgoomvKHptJnAId/feJZvu/rAsnPln/jm7859dmmiiXFQwgGGM4gse4RSWz7b4WrxANeP6hB2zJd4Vu63iFbahEwvRjUtJIzvLFl+KsSh+L0Rr4WRwxrCkzAa68AsX0FKH+yCaGCyzgSLojwaGiiZWcDBjujsK1OmMBkaLiJc53V2R865R8U0YT6Z7K5ZhJfYk77SKXQ3UOxTca42Ib8FEJNxHWwbvQHA+1nkd7YlbjtQT78P3IN9EaxJ7iifT+OeCezijXgtuBOctFueJb8dkkIdrWOtDxNIiG2Ltaob49Yj/RE+eeE8iPpTh68cR35isLUp2l6IVtyI2GZvLRHvYo4ormJvBOxOcy9PWR2IopzAfd4L7LWYqF8eD/BILcnjr8Du4RzGnBqcDDxPx3nri8CYS+hvgDib2G8Hu+Nx24xi+Rmw8rFwXlUj4l/Pop2N/4pRa17M4xBrCvEj6U6ABWIXTYcuJmKHh+CmpFKhDnHRVbC6aOBOkXd6O+0CdnBacx3usKLOZzuTc35vB6cDdxNery2wA9kXxvzgb9mnD+rDc52S6+8oWn8KJnMmu4jnWzJb4FHpxEa/xY6bT3UQTefgPjamlN2pLyT4AAAAASUVORK5CYII="
    }
  ],
  "quote": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAC9SURBVDiN1dEhbkJBEMbxH/AEAUtIJQaFay9QDR6DKqKGCyDBc4KK4nuDOg4AF0AhKxoUVGPmJcvrIynB0C/Z7GT++83u7PDvVYm9hTEaCfvCW8SveEjYD97xXY3EC/qF4lM8xZoWWD88skg0scIsOfQcedgV2CxnVTfq5gJ5C0cMnD+zk7CO3+2t0gJL1FAvuWSDRUzqz6rEGHsX+Acml8xtzOPnswJrYIQDumXmLvb4xGMJ32KN4TXt3LlOp3wa6Zx2cdgAAAAASUVORK5CYII="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAEJSURBVFiF7dYxSgNBFMbxn5IqpYI3EEE7sfICYm9ae09hcgBvYWGhWBmwtBAEtQyksFUrKyE24tqMMA5xdzZCEJw/PN6yzPfet4/Z2aVQKPwx9jBGVRMTnKAb6brh3qRBOw49fmTUUCCOXqTrtdCN4oaLiYH1kBdqYhDWbES6r+tBgzbuMdXA3CkGioFiIKXNQdSPdG0OoipumE7gEA8zGL/AKd5meuyW9KdMIJfGCeSwFPLTjLrn3xpYC/l+TrpvbOEDd9HHJZdhGP9O26YdrOIAL6HIZqZ2Gdthk1Y4b9t8N/nJeMV+pvYqefUusZIu6mQUescNrnGUbqIaKjziFmc4ztQVCv+MT3Q6aEB5A5qjAAAAAElFTkSuQmCC"
    }
  ],
  "refresh": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADJSURBVDiNzdIxTgJBFMbxnxgtIMTEws7S2mIJVzAU3sDWmHgACwqO4BWolRY6tDE2VBtPoBYmlhsSYrc0QwILmwEMCf9kqnnfN9+b99hHqujgEzkyvOMB9Zj4At8YIMFJOAn6+MB5qE2L4mN84REHJQ+08YtGSLfAHV5RiaS8wXiVwQtaEfHsX3L8FS8nOIsYLFGMW9b7WgYpmpsazHOP0X8MjvAWRlXGVWyZ6hiii0vUwiI18YwnnMaSHOI2jDXDD3q43qqvnTMFFMwh0uAE46sAAAAASUVORK5CYII="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAGXSURBVFiF7dY/SFVhHMbxT04R4pQX1CF0igZzCULRIYLAPxCEdCGaWl2sKQgcagrUUYQaanGVCFoCEQQzjEYtShwCF1FBC1q6Lu+BF7ldzz3n4B28DxxeOOf3vM/3Pee8Lz+aOu+6kMFzH2VcRRcq2MBPfMUrHBQNehHPcRgCa12/MYvLRYXfxnYU8A5TGEEJ7RjGMyxGdTsYrDLfMpbSht+NJlxHbwrPTWxFvscnnif3T9VIVDyRljioFa8j/0y9AB3hW1bwtM7wWONR4EI9AG9C0UqO8ER3osUspgHoif7mKwUAwA3sndgt/9WTUPA2Z+jyKdsVtFQx3gvjl5wA/2o8+1jLeBQIh3ICZFbyilrPIqzaJ0h0qVEA38LY1yiAz40GWAvj9bMAqKYO/Am7oaiDqG5NR0dxlqYlt0rYDxCTjQCA/uhMmMrgf4FdPMoD8TCC+ITuFJ4BfI985TwAMBZWkky4hpcYRRs68QDz2Izq/oZ+oBCVMJeyKa3gfcr2LdMfXsYtXIvOil/4gVV8CO15U02l0jGVB4Jot4/bMwAAAABJRU5ErkJggg=="
    }
  ],
  "edit": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAC7SURBVDiNzdBBagJBEEbhLzoavUQu4AnUGyhZegVPF4miwYUEFx7CS0gigugioJsKDDLtaNzkh1500a+q+vFgqje+e8YQe2zuHVLHHCts0f4LPEOGPr7QuRX+wDfeUYt6Dzu0oHIFHoejl9y9hk+s0YWnBPyGJl5xDHAUDas4YICf1NqLMJ9PMyROwkdS2LIAzkLkPAWLFYsmZyFxFkOSOaFRAE8wLYN/G6TWLoUvG9wNC3mn3Cn98//IGd+5KNyaKfmrAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAE8SURBVFiF7ZVLSgNBEIY/UETE5QyJTMBgFh7ClXfwQjmHh4jiwpUrNzlAHoNxjGACgbjICRw3NVA0o9NMd4/E5IeC6Qf1/V1QNbDXP9M5MAA+gVvgtEl4B5gDuYohcNI0PAWugLWsn4HjJuGR7F8CK9l/Ao6ahBe6UCYegcNQ8J8MmCbugQMf8DbwKknflZEJ0Cq53wOWcqfvCj8DZpLsA+gCiTKUikFT13K+calCW8EX0veFEiCTs8yoRCKVyoG7EPBCLcNEYsCnQFwXnkqSpZTd5m4GvMn32AVe9XJTkTLh9PK4Btw04ASfbjN89tfwsllgpQc1ZGzhsUzBHHhxgQN8SaLfWk0rAka+4KjWsYV7KXsdA0HgtgY0fO4TbmPAhHd8wqsMBIcjP428IoLBAW7U/C+LSUj4Xrunbw3Lm7TNZBhKAAAAAElFTkSuQmCC"
    }
  ],
  "export": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACxSURBVDiNtdIxDkFREAXQQ+iVOqXkR5RESalT2INlWIY10IpEIXqlHVBZgZZmvrzEl/9J3ORlXu7k3jfzZvgzFnE+olFi0C57of51TRUMusgK+CxypQYNbDFMuFFwZS2/0MMFexxwDe4NtYhTDOJ+wwp9HIMb4xwTyT/2hF3ewiYxbUU8Y5KI0xys00oeFVvroFmkqWpwSxbrJ4O3CvKx3LGsaJLjLtmD+ZdimP2g+QOenOAbT+KAJdsAAAAASUVORK5CYII="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAEBSURBVFiF7ZVNCsIwEEaf4sYDiNQuPIqXcOfWW7rQulXRhRT/qm48R9xMJcZEqk0QIR+EgWQ630tKJhBVTxkw/SWAkvG1mv5YIkAECAfQAObAAuhWyE+BJTDzwPcAWMt1OwE9bc28hilwkbmVLwBk54UUvoqRCZDKmpLcKqdVG6IE6Ic21yGOYnTWAG4SDyHNdYhCM1e+dj4EckthZXlwEu0kyp0nRk7mqJWL14u2jg8UMLHkJ8Ae2FnMEWhXva0NoPbLVlFPPn/RCb9VBxhLrCTfv2Aj9TbvfEKeQNuIVrUCAoyAwSePUrwFuURX8/A1dK8nDY32GmrsXK04KuonugMon5K4UQ34XgAAAABJRU5ErkJggg=="
    }
  ],
  "delete": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABeSURBVDiNY2CgEShkYGD4xMDA8B+KP0HFiAZfGBgYJJD4ElAxvOABko2E8ANchvwnwnUoapiI0IAX4DPgAg42XvCfRDZtvUCxAR9xsPEC+kcjCxr/ABGu2EOppdQFALXPIJgisKrJAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACsSURBVFiF7ZZRCoMwDIY/hofwNPMSntAnbyFeQga7gDDYBRTcS/YiTWhLO3DkhyCEv8nXtGDBFa8WGIAVOJRYxdPWABiNxucYawC8pfjd8HTiedUA+O6ulA+AWyA3KWM9N9DC8k0xADW1p5iTRplb59cTcIAiAHPoNhv5bGmXp1QernoEDuAA/wXQZKyZgS0hny3/GzrAIt/Yp7j1RlyMPqp64FkA4CG1XK6gPnoQa7IwmZzVAAAAAElFTkSuQmCC"
    }
  ],
  "remove": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABeSURBVDiNY2CgEShkYGD4xMDA8B+KP0HFiAZfGBgYJJD4ElAxvOABko2E8ANchvwnwnUoapiI0IAX4DPgAg42XvCfRDZtvUCxAR9xsPEC+kcjCxr/ABGu2EOppdQFALXPIJgisKrJAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACsSURBVFiF7ZZRCoMwDIY/hofwNPMSntAnbyFeQga7gDDYBRTcS/YiTWhLO3DkhyCEv8nXtGDBFa8WGIAVOJRYxdPWABiNxucYawC8pfjd8HTiedUA+O6ulA+AWyA3KWM9N9DC8k0xADW1p5iTRplb59cTcIAiAHPoNhv5bGmXp1QernoEDuAA/wXQZKyZgS0hny3/GzrAIt/Yp7j1RlyMPqp64FkA4CG1XK6gPnoQa7IwmZzVAAAAAElFTkSuQmCC"
    }
  ],
  "category": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACtSURBVDiNzdCxCcJAFAbgDxTEHdzAFaJCMI6QESwdy9LK3koQbBxDwShOEJs7CCGJ0coH19y7/+Pd45/qirLh3LDqA5Qt9wkKpH2BCfJab4HHJyQCOS4N/RT3LqTtC3XkGb71ExCRogl5IeuJZGGSafVyHuRlD2CEM9b1RhLkrm2PcMAew6YHaQcSw7u2cB2pLmpcCQ+6wlUkbnuM4zfhWMswyQnbb8OxZti0hd/pmyj8dOxmEwAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAFNSURBVFiF7ZW9SgNBFEYPKCKWQmQFYTFNnsHSR/ItfAHxASwtRBttLCRvIErUBVPEQmJpZZrY3IHLuOP87M1W+WBZCHfmnEyy38I66/zNA7DMuBbAFVBbCeTA9TUFDiwFUjMAJpYSuQLmEiUCbRKVpcAJ8CH3mMSLrG9KJdoE5vLZPGF9BbzK/FuJRJvAOfANnCXusS8nUCRR+h/wUymJRn6eXgWcxFT2m6RKWAogj2SWhLVAtsRCBs26vUXiCdgNDd7I0LtVt6vU0idL4CI0NACeVyhxLHv/ABuhoT1Vq5YSNTCTfU9jw2bdruDu+C//+/a+RNO12z34dSrcxW+0XImhB9/MXN9JYgh8yrrbUnhIItZoPnyrC1xLpDTaSMHvreAusVodAV8Kvm0Jj0n0Ag9JHCn4eNVwLTFTb1AH3+kD7nIIPAr8rm945/wCAxKjSyuJ/iQAAAAASUVORK5CYII="
    }
  ],
  "note": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACySURBVDiNvdIxDkFREAXQE7EZka+TKESjEZUlWMXXKhQa67AFhYQ9aPSE0g7QPPLC9z0hbjLJTN7MvXcmjz+jFqIQK1wKYhjeM+yxC/kTLiXKGU7I0Q1Edagk2M6wwAwjNHFOddDAEb1Q58FJI4WgjkM03I6tvyOoPSh3wvFuyoN3BGNMo+H9w+XvvWVHbGGCOfrYFDVVXwwvoryLbYlQ4QrJvSn/oBTxCusPXCy/Ff4drjEaKEQw2Th1AAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAEESURBVFiF7ZZJCsJAEEUf3kHisPFQ3taFuFZwE6NxvoluKlA2GapiN4jkQyNUm3qP6kYDQ/44GbADtsDE8+ASKICXca0b4Gf1nbNH4uCAv4BV8PxUwW/AXUlMLQJV4z7JBFoBZ8Bc1S6WSfQVCMeeSw2BHqW+TyGgx/5UYy9lb5ZSIAvgCxn7RWpXqZvvgUdAn/lD4HrvpPrd1JFEEWiDA4zV2M1wq0AyuEUgKbxLIDm8S6AIbnsIz1tu+6bhZ9slUO154V193QIh3DL2JAKeM48qEC7LhYsisK6Bl8a/2SgC36S27ygByJVB4CcFCvn0vJhalu7dmqV6m4m5TtJ7yJCPvAEf8dlY12QXPQAAAABJRU5ErkJggg=="
    }
  ],
  "code": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAC/SURBVDiNzdIxagJAEIXhT60ET6AXsI1iYxNSxjNIwMZC0lh5Au8hkoCHyA0EY+UdPIDpQtKMsJoJEZv4qtnZ/7FvhuW/VbuQm6ON9bWP7NG5xgwD7H67rBZ1E+94OmOGWEQ9wibYE/Ui5gr1ot/AB1pxrgezx90RegjoOUk4wlvSn+KA+yoqyThl/Jek/4mvwpuO0IpkjcKYjqAwbDGO8wyvZ8wkFv1jiZl2eLwEzNSNmH/+1Gxx0McylnXj+gYRdh/2lFK3iQAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAGDSURBVFiF7Za9SkNBEIW/q11AfYCYzkcwctFn0M4qICjxKbQ3WuojWIixsrCx8SdEREFQDCg+gUJIqwSzNieyxvuzK1cvSE6zl50zZ2ZnZ4cLQwyRLY6Bq7yClwED3Ps4jWSYwJLWvQw1nTEKdIAeUMwjgQWV/yyP4AAHSqCapWgJaACXKbwJ4A3oAuPWfqAX0ZCWF0LgRac6SeFWxduPsDVkewZmXINXdCIDHAGFFP65uPMRtoI0jDQXk4QCoCayATa1l4SiuB29hDjdLUt3I0rXzrSrKrhgXT7bDtyKtL9VNgAuZGgDs47BAZ7kV3bkz6laBmhiTUJjrSbe/wvKwBTwCFw7+vSAd+v7Ez+5gh3x1xyDx15BH4NNWEtoQp/R69SEg5mmPUPX0ev1DG2EakgDnEbY67KtpOg0reYOXYP3UQLugNbA/phO86rvOATAA3ALTPoGT8KqTlXPUtQHSaP31+Eyer3g+0u2rHXXGih/ipYqMJ1HcIAb4DCv4EP8T3wApJlyBuNtSCwAAAAASUVORK5CYII="
    }
  ],
  "sticky": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACsSURBVDiNzdIxCsJAEAXQpxDSCBYWnsMqlZ3XUURvoLdIb+cRvIG9So5ikNisIMmuxEo/bLN//mdm/vBPGGCNK2o0rVfjgmXKYIsbFsgjfB64G1YxgwpFj06L0EkHNbIeBhnuMaLpIe7UDr8QRdHHYBCW9p7OVyNsWukcUcYKU0t8T2cfEhjHDCrMIv+PYLwLY0xTs25xwrx1SA0OOGOSEkss63XCJUafxL/DE5P8KqOS5o8sAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAFfSURBVFiF7Za7SsRAGIU/xU6UCGJhIT6Ddlt6QV0bOx9AsLHQF1BWbFLoa4hoJ4o38BXstBPE2y5oJXZKbM5AWGLyT0wamQPDLjPnP+fszCT/QkBAPiJgG7gAOkBiHB3VtICBsuYLQNvD9LfxDMyUMXcCx8CkdsOKSDUnKZ05a/EQ8Kqi2Dd5BnZTOzFoKdhQwXUF5gA9wJU01ywFRyJPVxQAYF6a+xbyo8g+Z16EUWk+WMju0lSNTN3eGoy8EAL8uwB5vcOMsk/BIvBS0Bdu6gqQ1zsi4ElrzToCFPWOU62dWwV9A6yLf5ax5hrROzBuFXS/ZsTIPxR/qmt+U/OfwITVHG1VAswa+W8ZvWNLc9/Wc08jVvGlkd99ZHFqbsXXHJ3VhwT2gD5jgH7gQN+/gOUy5g5LKeFbYBUYKwhwp8820PiLuUPT859wogs5XIW5QwTs6D7khbnXmzAgwBs/Qp2cacJMvu0AAAAASUVORK5CYII="
    }
  ],
  "ai": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAD0SURBVDiNndLPKkVRGAXwnz/nGdSJpAyMjAyUqVdQhsyMzMTQI9yBKyXJK0jhAZSBASYyckdKdDOkhMmn9jntwz1Wrc6391rf+vY+bQbHTLCC4RYBy8F/oYevYG/QphMcJ+vtYAWjDc1zmEjqK5wl+lp894YaAnbwgBGMYz3RVnAY9WquucALymh+jqAUW8HKVRbRicn7iXYQe53wZK99jztsxOQ6SmyG5zYVft5BP1l/ZAI+k7qf0RVYwnkEdBNtN/ZOw1PkAlJM4S2OXUY92WSu/114xTTGMIsnHP01tY4FXOMG878Zm17iBR7xjsu201vhG1RaLah0NrcsAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAHtSURBVFiF7ZbJShxRFIa/BJMQjRAwiJjGJwjZRskriNr2SnDCdbvL8BQ+gFmIgmThRhBcdeOA7cYGiUlWWRvBARQUmpiQyuYvOBa32nt7EoI/NNw641/3DF3wn2Ib2LxLApF+t+Jh87m0jsC2483j59RyNJLA3yq6Pw3MwyjwEzgBRlJsvHsgFI+AM5PgVLKWEcgq8BfgQOecw24LKDjkdY/nqpK+Az7ovBbgX9fNdAHXCtALvNT5t3TVYCfkxmSETMGY6l0AjtSIG0CbdNXgmpDgySiL+ZSRzUhW9oxRcwkG5FgBnhl5p2SRbG5DWnM60Q5MAyXD/LPDbsXod+Tz1DeJC/3AJ+DKBK4Ai2q+JDLAkrmJCLgE5oE3IYlfm9mO1DgFYALo8PDvkG1RvpHZGa98CPyQw1fgPdATwj6BHu2Jb4r5Pc3QjqHPW4bAdnunj8OgYRyXoAiMB5Rg3FGCXx574gbSmnAB6HbYZ9SglcSmKwF54EVIcot4DHdN0DmH3bLRHwAfgb5ak6YhXkTHib6xi+hto5MmEa/iYSObkmyv2ckBZpVs1ciKkuVbQeC5/sGude5Wt8fPNaEtwPYCWAeGgEngCfBAsotaCYQipyvfN2s726rkAI+BczN2ZykfpU1FTp/khyrHPerCP5FhoKcmbPlaAAAAAElFTkSuQmCC"
    }
  ],
  "highlight": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAD0SURBVDiNvdK9SgNREAXgLzdZtbQWLcS3sLFMI/gDVlYpfA0fwdZKiKAighpJ4yv4BpaClQipJIioazML62Y1MYUHLre4d845M2cYjwY2f3pMY4oTjrE+gdAIMvRwEi7+hDnc4nwCl7Vo4xmz0xRnuMYgWmj99rnOXtHzYpBdxl1FAzt1BC/I8RbxtXBVISnSaVcJmpjHWigr7UAvSDJchMheqhSfYibsF8qwjQ/coI93dJAXBAndmPoWhqGcSso5VvCAXXyWrR/hrjLxZrQxiNOP/RhJIeEJS7jHPpZxFrYXsBGOXmuG/g2rOMAjDqdZ4f/HF34HLAkbjmrHAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAG1SURBVFiF7dW7ahRxFAbwHy5qZ7xsdmM2YOkD+ABWWlrb+B4+gLWFiI02Nj6HKNgY0YAxG42b4KUQBEFSZ2zOwGEwc1k2E9B81X9mzvy/79z5RzDGOl4fB/kEOyjw9jjI94L8c0Ti/yOf9k1+pUI+7JN8iO9Bvtk3OdwL8vdYXsSFpzraD9K5WISALriEjSDuPf+r2AriGXbj/KEPESN8CcLtEDMJIUUIO9I2fJgKb5Ter6URPMVKhzsvx+542aYID9I5F943XI8peBXP4+ImTPAC13C+jdoxPtX0fv7+sSEdeXFtt03dMEJc1IzecUSi3AuTQ8g7745hVHoRlb/bIKIUulMRMVfRZs9Lr5q8yCL2wn6u3TFOnk8rxTVpyPko/TvD11Q/Iy2Q83mY4rqcj0JYMc/UXEkhfIeLNbbZ0zLna4n8Fe7iEZbael7+/AYXWthvJi9nKdfrONeGtMTZNOsL3MbpGvvV6OOSOId8oyFyf8UyflTy9htPcQtnkm0ewbN4XsID3O/qecYAN/EEvypi9vEMd1JVV3t9oRjgBh7jZ0VM3bQ7MjE5Mlstl84JTtAKfwBxHKv9/Bl3bAAAAABJRU5ErkJggg=="
    }
  ],
  "underline": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACOSURBVDiN3dJBCoFBHIbxH9+3tJAzUMotlHIEZ+FCriDcwUoWygmUAxCbbyymYYaVPJtp3vc/T9M0/CW7L7sn90+6dtGd3vCbgivqRF43XVZwQj+RD3AsEawxj7oKC6zi4VZC0MMGnWatMMYZU1xygpBPMMINe2xT/yAWDDF7IQ0scQib+A26mcOlM+U8ALDoFEJs0OC8AAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADjSURBVFiF7dY9SgRBEEDhTxc8gmggGpoYaGasmIo3MDE0MPIIegoj77EIJhqIybJHWL2AIKw/SQnLimPP2E5UD4qCnuqqN0xQQ5Ikv3ODYY/3vvER8S/3Frs51SMFUiAFUqBE4CnySou+q3N3/yTwGHm7hcBO5IeaAictBE5LBUrYwGsslr2C+sOofcF6DQE4j6YT7DfUHeA5as9qDYcB7mZW7HW86TLWcBRnX89vsVBTAJZwibeZQfMxxUXUFtHFchfH2MQW3jHCGFe479Az+ZFhw/cujcYf0z52wbSHGUl3PgGjGz+oGfa5IwAAAABJRU5ErkJggg=="
    }
  ],
  "strikeout": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADESURBVDiNzdK/SkJRHAfwjxqYTTcIEnoLm8o5H8AXaJMGh96lxRZnX8ChQUIwCOwtInQyuIsNDS1HsDj33rPldzp8f1++39+fw3+jVlK7RgdnWGKaanCKZxxjgQ/08Ik+vqq6esBjJGiCQeVMeEE3RQiNCJeHmbcpBvs7uEM7MXiNERztkVmBuIVbnGOM9xJtIRq4xyxF/IqTCJ9h85esR4Q5hhF+GMx/IfaRLvAUanM0w1m/cYNVlcEOV7gM77dY+mHgB6drHLBxmLEHAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAFgSURBVFiF7dYxS1xBFIbhR9k0QURUUgU7FYSAVexUkn+QYG0j2FlpK2LnX7ASUqWy00YRUTApE5IiqRRblUXSKBu1yFlYRHfnhrmIcF8Yppgz5/vmcmbuoaLimVHDR2ziCre4xE9sYKpM8bf4HaLtxgFGcot/QCMETjGH/ljrwyTWcNbyVYZzifdHwlus42Wb2EHsRuyXXAbmIuFXdCXE9+BX1ERHagkxb2L+FEY68QejKeLQnRqYaLYwKQY+4wL1MgxUPMRewmPzv2PvvliRIsxBo6zEQ1iMf0LztCtlibWjhuUWE5NPYQJWw8B2jmT7DxVPB16HgbMcBuqRbLDAnlex57xTYMotOIp5voCBhZgPC+x5lIk4zXWYaPdHrMVtuMFfjOcwwL8r1azsb5hBb8v6AGbvdUxLucSbvMdJwmt3jHepSVMajFZeRHs2jbHoFW7wA9+xg60yX7yKiuzcAa+ibZ1w/9HzAAAAAElFTkSuQmCC"
    }
  ],
  "summarize": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAA9SURBVDiNY2AY8oARiT2ZgYFhGQMDw3EGBoYMBgYGCTz6XjAwMMxgYGBgYMKhQICAxYTk6QhGw2A0DKgCAK3xDGqeYc34AAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABdSURBVFiFY2AYBaNgFGACUQYGhhQoPSDgAgMDw38ojQwOQsUpwfvRLWPC4gAONBoG/lHBc3+IUWTCwMBQzMDAYEwFC0fBKCALjJYDo+XAKBgFo+XAaDkwCkbByAIAtWdGimD49w0AAAAASUVORK5CYII="
    }
  ],
  "explain": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACGSURBVDiN3dExDoJAFIThT+MBjD29tYWegdbKa3ANTuIdLGzhBh7DCivFZkMIyYZFqJxkmsnO5M9b/kY5GrSJbkLHOgycUGKV6DJ0uoGftYnke1wG2RWP4cMYwTYxiw48E7P5BLEbVMGjWvwXdrjhMNJ74dwfaJGhxh1HvKeQ5PigmMS/hL6WaRuktc4RbgAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAC3SURBVFiF7da7CQJBFEbhDy3AAuzCyA6MTMQWLMGCbEQxMzRwZQML0ALMfCW74AN1RGdFnAMDMzDc/zDcgUsikbikjxzHSCsvMu6SRQwvV/ZIoLwUi5v6tYhhQSSBnxOYBnT5JKbAIeDO7sWaF6Rv+IzUA+/y+z2QBL4i0MTsQ8MILB6FXXdpC5sPTkNL9EIFOtgW5zEaAa/1NqXAAPtiP0K9inBYnUkcMKwquKSNNeboVh3+n5wA7oyOMYmuANsAAAAASUVORK5CYII="
    }
  ],
  "title": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABBSURBVDiNY2AYduAFAwPDfwL4BT4D/qPxG6AYpxomNMmPRLgSRQ26AQJEGICiBt0AksGoAbhBApYElEArywYYAABVTROT1aAthgAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABvSURBVFiF7ZYxDoAwDAMN4v9fqvouEGGBBaVVAkYd8End0viqdAgghGhTABjplFbI1BEw8oPcrOXpxRNL1LjMAYFPGS7QG0EFsBIyWH1c7O1nHT4CCUhAAhKQQFag3jadi9D2wxDYAzVbsqcQP+cA7Yslfi8yP6UAAAAASUVORK5CYII="
    }
  ],
  "authors": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADpSURBVDiN3dG/K4VhGMbxD8XmnHe2KGWQOhkcP4rBINmk1Plrzqzk1JkMBhlYRKdkZ5Aog0k2KROSWCyy3G+9PT3Zucbvc13X033f/CsNootHfOIK0/HWwzMesImBXEEP25hADau4xxSaKDCGHeym4RmcZUoXcJrhd1iC/orxOmO8wVyGn2C5WvCCesZYx1uGD+O1CopY3khi3EI7YfPx4Wja2sQHDtHBLY7RF+8rOMIXJstQOcIs9uJUpd5jURtxtgLfeMJB5cQaYW5lZq3FcvcT3orMOFxgLRMuNYRLLCZ8Hee/5P6KfgBnwCtv8OgqwQAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAH+SURBVFiF7dbLS1VRFMfxD04yNAuJyCQsMAgKCSko7DWIHkLQvAY2DqKGEYGGSP9DNAkaRGQDBxE06DmJMoMIIiqzQMs0atBrcpusC8ernb1t2v3BYcM53/Vb6+y1z96Huuqqq1y7MIh7+BbjIHoWYI/iCsbwHU9wKTwWrRVhVim5LmN5IWayhL0YnlnaiA8ROIP+eIsW7MYAZuP5BDZEXA/OYA+a0Y3z4VHBMzTlFPAwAq7XvGFRrRgO7n7Cbx2eBzuSSn48wDcZ1TZjPPhjCXYZPgd7pAy8m2lYVV/wtzPYC8EOl0HV3m/KLKCrMGMpdQY7XgZVV22umhcZM49tqAE+xdiVadgZ42QGW/WcLiug2p8tmQV018SVqTfGm2XQ3piiMTQmDJfgRfA7E2wLvga7OVXpVIBXS4poxLXg3if82vAo2Fup5LAj+lTBKxxARzzrwMG4X8FHbPuLz3acKni9xJqcAsTu9SVxFsxg7QKxh+IwKrLTWJWbvBejieTVaxT7Fyggl52jdjwoBEzhLLYWpq49pvxcYa1UcAera/za4is5jXcJVhOeFqATmbN1shDzGEtL2L5CW+exI4UtNXcPqKq7cCjdSLAr46dmDjsUNyYLq32xWl9oSX+CbcXrYAca8Bs/sC969S96G/ET+JVgZ3EYPyN3XXX95/oDyoizfM1u44UAAAAASUVORK5CYII="
    }
  ],
  "year": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAABJSURBVDiNY2CgAciAYmLF4WA/AwPDfyLxfmwG/IfSFVCMDpDF/2ORxy6IA8DVslBgCHVcwESJjaMGUMkA5HRwgISo3EOpxdQDAIfqGH292HeJAAAAAElFTkSuQmCC"
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACTSURBVFiF7ZZBCoAgEEV/0RG9b3QIQ+goLWzjwmjQGdIK+g8GIYbva3QhQHQsAOaO/VViqub9o/DNAQhZSB4UlSX1h5RdxRs2spbXCEjja3EEYsakDFwA7AYBa/8J69/eypUu4aOUjqDHFC58egJD473Eib4+AQpQgAIUoAAFJIE1ra0fpHl2EQdg6yCgfpaTf3EAgkluUeM2XDQAAAAASUVORK5CYII="
    }
  ],
  "venue": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAEHSURBVDiNvdJPK4RRFAbw3yBWirKRBWVr6U/EWm/hK/gGykaxmmE3Cx/A1iewUmQrMmgiRbNhY6WsJrJgc9669A4j5anTPadzn3Ofc87lj+hs814fMiyijreiSxmaeA9rYhWn4R/hBCspqSPxp1BFKayKdTQwgA3cY7qVzHLyem77eMItDrETBQsVQCVRUIl+ezGHTVxiFP05oeuH4b3gGg+4wg3uMIGDIgUp8jZqWAvSMvYw2aqFIpwFOY3Hf1OgVlBgJg++m0EpzjqGMYQRjMVaB/GYEorWWI7cMV5xjt0Y6FJRC1/XmMreip/ZQE+o+YQs1pZ+5fnIzeIZF9jGArrbmN8/4APp0EGsg698pQAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAH+SURBVFiF7dZLaxRREAXgL1FQXKj4yEKFCKKYxAcomfjYKrhV8wMUXOhGcOvPiLgWxIDgf4gr0YxRUMcoiqiLuBCjiCEQHxk31dCavjPTOr3RHLjUbep0zZlbp7uaZfwj6MEgzuIKHuIbnmDvnxQcxTSaiTUdnAHcwlwL7u12yovQwFAbkU9z/xxmUY81iUeYwSJWx4l0jEx9u/yHiAcTvOeRP5QqtLKMqgK8wUasxQrsRw0jsXYFr4Z7ZQqn+vn7uhrxNRZa8G5UdQJTEbdHnIn+Zz7owQSGyxbu1AODEWfRV8BbFSZsYn0VAnoxH/vN8YNHcQk3ozUZ93gVAsRz3sQL/Gjhg8tFhXrLqErgfsSdUe8lxnExHr/zkS/lgzIncDr2dawr4A5F/l1VAvpj/znBzftkWxUC4H1c70jwJyJ/skhdN1CPWEvkJ1P5bgsYaZNPCVyCsi04Edd3E/xNkZ+vSsCGuP6aeL334VNwducTfzsLMnzEqzDh4ZiM2USsYWuOOxxjuiU6nYZ5jLfgLcTobmIsf1O3TAgPIi7GJ9s1XMABrMG5yP9i1HYtSH2yFfkjc/oz7CnIz0XsLyOgDKZiGA1gC/aFH2o4El9NYmi1RaOD/jcK7rvTgv8F1xPzYglG4yhTxR7jVMF9x/AW32NKjuFMnEqqncv4z/ET8E3VvsHIvH8AAAAASUVORK5CYII="
    }
  ],
  "addedAt": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAADySURBVDiNpdO9SkNBEAXg74paipU/IMFWUJsQgp2NSoIPYukDiMQnsLXwQRI7LRRURCLY+IOFQrQVbGxs9sJlvWuu5MAUe2bPzBlmlxGRJfhJrKIeztfo47tK0TY+8IDjEI94x+YwcQfnaJbk1nCF/ZR4C6fRWDshcmQ4w0YsnsYTFkocdSJuEc+YgrFAbuMNr8NmxAsGaMF4IGdxlxCsF1wMcIRbzBcLfCZW2i0ZNXf+VUw0cVHBfo5LNIpEhhusVBDXwzp/OW6kElGjPpZTFw7Qw0xJbg4n2IsrxmjhEPfhbUyghiXshgZ/FjDqZ/oXfgBFTSvYJq9XIQAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAINSURBVFiF7ddJaxVBFAXgLwYjwYAgEkQxutEEEhE1SoSsHcAZ/4Wg4B8QBNGFIA5/QRAVN6KiLjQQDSrEhQtBETFZPCdwBEEi7eY+aR5Jv+qXDtnkQFFN97nnnu6u4RYLmGe0leT34SB2YQ1Wxv0aJvEAV/GuaqN9uIsssd3C+ioSt+M0/obwe1zEIQygK9oADuMSJoI7hZNY1GrybjwJse84isUJcR04jh8RO4IVZZMvwfMQqKG/hRfoj9gMz0IzGdcj8DN6CngjeFjwfC0+hdaV1ORHIuAPtjfh1gddEYZiPGTYn2LgVZBPJXBTDMCZ4I03m/o7gvgRnRUa6MKX4G7LP2icIvuiv4bfCcKp+IUbcb23yMBg9LcrTF5HXXOwiFT//6sSRVN/gZhNGV4WkX4GqaOkgZlafop2xr2veYGZlsn2RAOPmjyfmiZXofbbcLku0UAZbAjt1/mbjV/gQ/Sb5sDA5uhrRQaeRr9nDgzsbsgxLYbiM33DsgqTL4+1IMPWZuT6Lni2QgPnQ/NxCnk4txkNVZB8OLcZbUkNupCrBVbPInlPbOkZzpUJbMdYBE6it4Xk+YJkrMTa8h/deJEblMdKlGQnciXZeCslWR1duJdbWhuL0qUxWzZGUXo5V5RmuBOcWaEtzgKjJcryURxIOXeUPZj0xtvvjAGWP5hM4D5u4k1r77qAecA/NIKdAmiOzY0AAAAASUVORK5CYII="
    }
  ],
  "filePath": [
    {
      "scaleFactor": 1,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACVSURBVDiN7dKxCQJBEIXhz/NMFIwsSAyvC63kcsES7EHQVIyMDAzFGowvEjQZcRFlFQQTf1iGeSyPN8zwa1pRB5igG/0FC+xzBkXUMapE72CNUc6gjNp70M/YYYlZ9CkN5jiVXrON94wqxpymBhvUuchBfUtdZL9m+Bvc76CJ1by7hSFW0A7hiH5imOMQh9R8HPnrXAGYNRaag5RSBgAAAABJRU5ErkJggg=="
    },
    {
      "scaleFactor": 2,
      "dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAACMSURBVFiF7ZZBCsIwEEUfHqEguOulCkIv6Wm0LRVyj27iZgSJpBXhaxf/wScEQuYxDCRgzM7ogBuQK1mAC9CqBK4rxV+TgJNC4FmgxhEY4swc+58KlBID0CgEVBljzv4mkGPONgVUvN1/EBb7CAtYwAIWsIAFSoEpVtVTTHxiqvTAXSiQgLOml8Z8yQMhCIQzrqJXBAAAAABJRU5ErkJggg=="
    }
  ]
}
