import { createRef, useState } from 'react'
import { cleanup, fireEvent, render, screen, waitFor, act } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import LatexSourceEditor, { type LatexSourceHandle } from '../../src/renderer/components/latex/LatexSourceEditor'

vi.mock('react-i18next', () => ({ useTranslation: () => ({ t: (key: string) => key }) }))
afterEach(cleanup)

function setup(initial: string) {
  const handle = createRef<LatexSourceHandle>()
  const position = vi.fn()
  function Editor() {
    const [value, setValue] = useState(initial)
    return <LatexSourceEditor ref={handle} value={value} onChange={setValue} onPositionChange={position} />
  }
  render(<Editor />)
  return { handle, position, input: screen.getByLabelText<HTMLTextAreaElement>('latex.source') }
}

describe('LaTeX source navigation and insertion', () => {
  it('preserves text selected by search when inserting a workspace figure', async () => {
    const { input, handle } = setup('\\begin{document}\nLocal source.\n\\end{document}\n')
    fireEvent.keyDown(input, { key: 'f', metaKey: true })
    const search = screen.getByRole('textbox', { name: 'latex.find' })
    fireEvent.change(search, { target: { value: 'Local' } })
    fireEvent.keyDown(search, { key: 'Enter' })
    fireEvent.keyDown(search, { key: 'Escape' })
    act(() => handle.current!.insert('FIGURE\n'))
    await waitFor(() => expect(input).toHaveValue('\\begin{document}\nLocal source.\nFIGURE\n\\end{document}\n'))
  })
  it('starts with the first match and keeps Enter navigation in the search field', async () => {
    const { input } = setup('alpha beta alpha')
    fireEvent.keyDown(input, { key: 'f', metaKey: true })
    const search = screen.getByRole('textbox', { name: 'latex.find' })
    await waitFor(() => expect(search).toHaveFocus())
    fireEvent.change(search, { target: { value: 'alpha' } })
    fireEvent.keyDown(search, { key: 'Enter' })
    expect(input.selectionStart).toBe(0)
    expect(search).toHaveFocus()
    fireEvent.keyDown(search, { key: 'Enter' })
    expect(input.selectionStart).toBe(11)
    expect(search).toHaveFocus()
    fireEvent.keyDown(search, { key: 'Enter', shiftKey: true })
    expect(input.selectionStart).toBe(0)
  })
  it('inserts a figure inside the document when the cursor is past its end', async () => {
    const source = '\\begin{document}\nText\n\\end{document}\n'
    const { handle, input, position } = setup(source)
    input.setSelectionRange(source.length, source.length)
    fireEvent.select(input)
    act(() => handle.current!.insert('FIGURE\n'))
    await waitFor(() => expect(input).toHaveValue('\\begin{document}\nText\nFIGURE\n\\end{document}\n'))
    await waitFor(() => expect(position).toHaveBeenLastCalledWith(4, 1))
  })
  it('navigates to an outline line and inserts at the selected source position', () => {
    const { handle, input } = setup('First\nSecond\nThird')
    act(() => handle.current!.revealLine(2))
    expect(input.selectionStart).toBe(6)
    act(() => handle.current!.insert('Inserted '))
    expect(input).toHaveValue('First\nInserted Second\nThird')
  })
  it('finds and replaces text without leaving the editor', async () => {
    const { input } = setup('alpha beta alpha')
    fireEvent.keyDown(input, { key: 'f', metaKey: true })
    fireEvent.change(screen.getByRole('textbox', { name: 'latex.find' }), { target: { value: 'alpha' } })
    fireEvent.click(screen.getByRole('button', { name: 'latex.toggleReplace' }))
    fireEvent.change(screen.getByLabelText('latex.replacement'), { target: { value: 'gamma' } })
    fireEvent.click(screen.getByRole('button', { name: 'latex.replaceAll' }))
    expect(input).toHaveValue('gamma beta gamma')
    fireEvent.keyDown(screen.getByRole('textbox', { name: 'latex.find' }), { key: 'Escape' })
    await waitFor(() => expect(input).toHaveFocus())
    expect(screen.queryByRole('textbox', { name: 'latex.find' })).not.toBeInTheDocument()
  })
})

it('reveals and selects a source line for inverse PDF navigation', () => {
  const { handle, input, position } = setup('First\nSecond\nThird')
  act(() => handle.current!.revealLine(2, true))
  expect(input).toHaveFocus()
  expect(input.selectionStart).toBe(6)
  expect(input.selectionEnd).toBe(12)
  expect(position).toHaveBeenLastCalledWith(2, 1)
})

it('offers proofreading and custom AI editing for a selection, and dismisses on Escape', () => {
  const onAi = vi.fn()
  render(<LatexSourceEditor value="Some bad text" onChange={vi.fn()} onAi={onAi} />)
  const input = screen.getByLabelText<HTMLTextAreaElement>('latex.source')
  input.setSelectionRange(5, 8)
  fireEvent.mouseUp(input, { clientX: 80, clientY: 90 })
  expect(screen.getByRole('dialog', { name: 'latex.aiSelection' })).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: 'latex.proofread' }))
  expect(onAi).toHaveBeenLastCalledWith(5, 8, undefined)
  fireEvent.mouseUp(input)
  fireEvent.change(screen.getByRole('textbox', { name: 'latex.editWithAi' }), { target: { value: 'Make it concise' } })
  fireEvent.submit(screen.getByRole('textbox', { name: 'latex.editWithAi' }).closest('form')!)
  expect(onAi).toHaveBeenLastCalledWith(5, 8, 'Make it concise')
  fireEvent.mouseUp(input)
  fireEvent.keyDown(document, { key: 'Escape' })
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  input.setSelectionRange(0, 0)
  fireEvent.mouseUp(input)
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
})


it('retains a multiline selection while entering an AI instruction and clears stale highlights after editing', () => {
  const value = 'First line\nSecond line\nThird line'
  const { container, rerender } = render(<LatexSourceEditor value={value} onChange={vi.fn()} onAi={vi.fn()} />)
  const input = screen.getByLabelText<HTMLTextAreaElement>('latex.source')
  act(() => input.focus())
  input.setSelectionRange(6, 22)
  fireEvent.select(input)
  fireEvent.mouseUp(input)
  const instruction = screen.getByRole('textbox', { name: 'latex.editWithAi' })
  act(() => instruction.focus())
  fireEvent.change(instruction, { target: { value: 'Rewrite this' } })
  const layer = container.querySelector('.latex-selection-layer')!
  expect(layer).toHaveAttribute('data-visible', 'true')
  expect(layer.querySelector('mark')?.textContent).toBe(value.slice(6, 22))
  expect(input.selectionStart).toBe(6)
  expect(input.selectionEnd).toBe(22)
  fireEvent.keyDown(document, { key: 'Escape' })
  expect(input).toHaveFocus()
  expect(layer).not.toHaveAttribute('data-visible')
  fireEvent.blur(input)
  rerender(<LatexSourceEditor value="Changed source" onChange={vi.fn()} onAi={vi.fn()} />)
  expect(layer).not.toHaveAttribute('data-visible')
})

it('pairs braces, indents environments, toggles comments, and keeps every edit undoable', async () => {
  const { input } = setup('\\begin{figure}')
  input.setSelectionRange(input.value.length, input.value.length)
  fireEvent.select(input)
  fireEvent.keyDown(input, { key: 'Enter' })
  expect(input.value).toBe('\\begin{figure}\n  ')
  await waitFor(() => expect(input.selectionStart).toBe(input.value.length))
  fireEvent.keyDown(input, { key: '{' })
  expect(input.value).toBe('\\begin{figure}\n  {}')
  fireEvent.keyDown(input, { key: 'z', metaKey: true })
  expect(input.value).toBe('\\begin{figure}\n  ')
  fireEvent.keyDown(input, { key: 'z', metaKey: true })
  expect(input.value).toBe('\\begin{figure}')
  fireEvent.keyDown(input, { key: '/', metaKey: true })
  expect(input.value).toBe('% \\begin{figure}')
  fireEvent.keyDown(input, { key: '/', metaKey: true })
  expect(input.value).toBe('\\begin{figure}')
  fireEvent.keyDown(input, { key: '{', isComposing: true })
  expect(input.value).toBe('\\begin{figure}')
})

it('supports whole words, case, regex captures, single replacement, and undo', () => {
  const { input } = setup('Alpha alphabet alpha42 alpha')
  fireEvent.keyDown(input, { key: 'f', metaKey: true })
  const search = screen.getByRole('textbox', { name: 'latex.find' })
  fireEvent.change(search, { target: { value: 'alpha' } })
  fireEvent.click(screen.getByRole('button', { name: 'latex.searchOptions' }))
  fireEvent.click(screen.getByRole('button', { name: 'latex.wholeWord' }))
  fireEvent.click(screen.getByRole('button', { name: 'latex.matchCase' }))
  fireEvent.click(screen.getByRole('button', { name: 'latex.toggleReplace' }))
  fireEvent.change(screen.getByLabelText('latex.replacement'), { target: { value: 'beta' } })
  fireEvent.click(screen.getByRole('button', { name: 'latex.replaceOne' }))
  expect(input.value).toBe('Alpha alphabet alpha42 beta')
  fireEvent.keyDown(input, { key: 'z', metaKey: true })
  expect(input.value).toBe('Alpha alphabet alpha42 alpha')
  fireEvent.click(screen.getByRole('button', { name: 'latex.regexSearch' }))
  fireEvent.change(search, { target: { value: 'alpha(\\d+)' } })
  fireEvent.change(screen.getByLabelText('latex.replacement'), { target: { value: 'key$1' } })
  fireEvent.click(screen.getByRole('button', { name: 'latex.replaceAll' }))
  expect(input.value).toBe('Alpha alphabet key42 alpha')
  fireEvent.keyDown(input, { key: 'z', metaKey: true })
  expect(input.value).toBe('Alpha alphabet alpha42 alpha')
  fireEvent.change(search, { target: { value: '[' } })
  fireEvent.click(screen.getByRole('button', { name: 'latex.searchOptions' }))
  expect(screen.getByRole('alert')).toHaveTextContent('latex.invalidRegex')
})

it('limits replacements to the captured selection even after search takes focus', () => {
  const { input } = setup('one one one')
  input.setSelectionRange(4, 7)
  fireEvent.select(input)
  fireEvent.keyDown(input, { key: 'f', metaKey: true })
  fireEvent.click(screen.getByRole('button', { name: 'latex.searchOptions' }))
  fireEvent.click(screen.getByRole('button', { name: 'latex.selectionOnly' }))
  fireEvent.change(screen.getByRole('textbox', { name: 'latex.find' }), { target: { value: 'one' } })
  fireEvent.click(screen.getByRole('button', { name: 'latex.toggleReplace' }))
  fireEvent.change(screen.getByLabelText('latex.replacement'), { target: { value: 'longer' } })
  fireEvent.click(screen.getByRole('button', { name: 'latex.replaceAll' }))
  expect(input.value).toBe('one longer one')
})

it('retains caret, scroll, find settings and undo across file remounts, including external AI edits', async () => {
  const handle = createRef<LatexSourceHandle>()
  function Harness() {
    const [text, setText] = useState('first\nsecond')
    const [visible, setVisible] = useState(true)
    return <><button onClick={() => setVisible(!visible)}>Switch file</button><button onClick={() => setText('AI result')}>Apply AI</button>{visible && <LatexSourceEditor ref={handle} sessionKey="session-test" value={text} onChange={setText} />}</>
  }
  render(<Harness />)
  let input = screen.getByLabelText<HTMLTextAreaElement>('latex.source')
  input.setSelectionRange(6, 6)
  fireEvent.select(input)
  fireEvent.keyDown(input, { key: 'Tab' })
  await waitFor(() => expect(input.selectionStart).toBe(8))
  input.scrollTop = 45
  fireEvent.scroll(input)
  fireEvent.keyDown(input, { key: 'f', metaKey: true })
  fireEvent.change(screen.getByRole('textbox', { name: 'latex.find' }), { target: { value: 'second' } })
  fireEvent.click(screen.getByRole('button', { name: 'latex.searchOptions' }))
  fireEvent.click(screen.getByRole('button', { name: 'latex.matchCase' }))
  fireEvent.click(screen.getByText('Switch file'))
  fireEvent.click(screen.getByText('Switch file'))
  input = screen.getByLabelText<HTMLTextAreaElement>('latex.source')
  expect(input.selectionStart).toBe(8)
  expect(input.scrollTop).toBe(45)
  expect(screen.getByRole('textbox', { name: 'latex.find' })).toHaveValue('second')
  fireEvent.click(screen.getByRole('button', { name: 'latex.searchOptions' }))
  expect(screen.getByRole('button', { name: 'latex.matchCase' })).toHaveAttribute('aria-pressed', 'true')
  fireEvent.keyDown(input, { key: 'z', metaKey: true })
  expect(input.value).toBe('first\nsecond')
  fireEvent.click(screen.getByText('Apply AI'))
  expect(input.value).toBe('AI result')
  fireEvent.keyDown(input, { key: 'z', metaKey: true })
  expect(input.value).toBe('first\nsecond')
  fireEvent.keyDown(input, { key: 'z', metaKey: true, shiftKey: true })
  expect(input.value).toBe('AI result')
})

it('completes citation keys and labels from other project files and environments', async () => {
  function Harness() {
    const [value, setValue] = useState('')
    return <LatexSourceEditor value={value} onChange={setValue} projectSources={['@article{paper2026, title={Study}}', '\\label{sec:intro}']} />
  }
  render(<Harness />)
  const input = screen.getByLabelText<HTMLTextAreaElement>('latex.source')
  fireEvent.change(input, { target: { value: '\\cite{pap', selectionStart: 9 } })
  fireEvent.click(screen.getByRole('option', { name: 'paper2026' }))
  expect(input.value).toBe('\\cite{paper2026')
  fireEvent.change(input, { target: { value: '\\ref{sec:', selectionStart: 9 } })
  fireEvent.keyDown(input, { key: 'Tab' })
  expect(input.value).toBe('\\ref{sec:intro')
  fireEvent.change(input, { target: { value: '\\begin{fig', selectionStart: 10 } })
  fireEvent.click(screen.getByRole('option', { name: 'figure}' }))
  expect(input.value).toBe('\\begin{figure}\n  \n\\end{figure}')
  expect(input).toHaveAttribute('wrap', 'soft')
  fireEvent.click(screen.getByRole('button', { name: 'latex.softWrap' }))
  expect(input).toHaveAttribute('wrap', 'off')
})

it('replaces regex matches with lookaround context and refuses stale completion ranges', () => {
  const { input } = setup('foobar foobar')
  fireEvent.keyDown(input, { key: 'f', metaKey: true })
  fireEvent.change(screen.getByRole('textbox', { name: 'latex.find' }), { target: { value: '(?<=foo)bar' } })
  fireEvent.click(screen.getByRole('button', { name: 'latex.searchOptions' }))
  fireEvent.click(screen.getByRole('button', { name: 'latex.regexSearch' }))
  fireEvent.click(screen.getByRole('button', { name: 'latex.toggleReplace' }))
  fireEvent.change(screen.getByLabelText('latex.replacement'), { target: { value: 'baz' } })
  fireEvent.click(screen.getByRole('button', { name: 'latex.replaceAll' }))
  expect(input.value).toBe('foobaz foobaz')
  fireEvent.change(input, { target: { value: '\\sec', selectionStart: 4 } })
  expect(screen.getByRole('listbox')).toBeInTheDocument()
  input.setSelectionRange(0, 0)
  fireEvent.select(input)
  expect(screen.queryByRole('listbox')).not.toBeInTheDocument()
  fireEvent.keyDown(input, { key: 'Tab' })
  expect(input.value).toBe('  \\sec')
})

it('keeps options and replacement available together, with keyboard replacement and Escape focus return', async () => {
  const { input } = setup('text text')
  fireEvent.keyDown(input, { key: 'f', metaKey: true })
  expect(screen.queryByRole('button', { name: 'latex.matchCase' })).not.toBeInTheDocument()
  const toggle = screen.getByRole('button', { name: 'latex.searchOptions' })
  fireEvent.click(toggle)
  fireEvent.pointerDown(screen.getByRole('button', { name: 'latex.toggleReplace' }))
  fireEvent.click(screen.getByRole('button', { name: 'latex.toggleReplace' }))
  expect(screen.getByRole('group', { name: 'latex.searchOptions' })).toBeVisible()
  const replacement = screen.getByLabelText('latex.replacement')
  await waitFor(() => expect(replacement).toHaveFocus())
  fireEvent.change(screen.getByRole('textbox', { name: 'latex.find' }), { target: { value: 'text' } })
  fireEvent.change(replacement, { target: { value: 'word' } })
  fireEvent.keyDown(replacement, { key: 'Enter' })
  expect(input).toHaveValue('word text')
  fireEvent.keyDown(replacement, { key: 'Enter', metaKey: true })
  expect(input).toHaveValue('word word')
  fireEvent.keyDown(replacement, { key: 'Escape' })
  expect(screen.queryByLabelText('latex.replacement')).not.toBeInTheDocument()
  expect(input).toHaveFocus()
})

it('shows invalid regex feedback without opening options and disables replacement', () => {
  const { input } = setup('text')
  fireEvent.keyDown(input, { key: 'f', metaKey: true })
  fireEvent.click(screen.getByRole('button', { name: 'latex.searchOptions' }))
  fireEvent.click(screen.getByRole('button', { name: 'latex.regexSearch' }))
  fireEvent.click(screen.getByRole('button', { name: 'latex.searchOptions' }))
  fireEvent.change(screen.getByRole('textbox', { name: 'latex.find' }), { target: { value: '[' } })
  expect(screen.getByRole('alert')).toHaveTextContent('latex.invalidRegex')
  fireEvent.click(screen.getByRole('button', { name: 'latex.toggleReplace' }))
  expect(screen.getByRole('button', { name: 'latex.replaceAll' })).toBeDisabled()
})

it('clamps the cursor and updates status after a shorter external revision without losing undo', async () => {
  const position = vi.fn()
  function Harness() {
    const [value, setValue] = useState('one\ntwo\nthree\nfour\nfive')
    return <><button onClick={() => setValue('one\ntwo\nend')}>Restore revision</button><LatexSourceEditor value={value} onChange={setValue} onPositionChange={position} /></>
  }
  render(<Harness />)
  const input = screen.getByLabelText<HTMLTextAreaElement>('latex.source')
  input.setSelectionRange(19, 19)
  fireEvent.select(input)
  expect(position).toHaveBeenLastCalledWith(5, 1)
  fireEvent.click(screen.getByText('Restore revision'))
  expect(input.selectionStart).toBe(11)
  expect(position).toHaveBeenLastCalledWith(3, 4)
  fireEvent.keyDown(input, { key: 'z', metaKey: true })
  await waitFor(() => expect(input.selectionStart).toBe(19))
  expect(input.value).toBe('one\ntwo\nthree\nfour\nfive')
  expect(position).toHaveBeenLastCalledWith(5, 1)
})
